### ISSUE TITLE
每日备份邮件，附件为空

### ISSUE THREAD

**Issue by SoDa-GitHub** [NimaQu/ss-panel-v3-mod_Uim#108]
每日备份邮件，附件为空，如何解决？文件夹权限问题？还是什么其他问题。。。

**Comment by xcxnig** [comment]
@SoDa-GitHub php -n 去掉 -n

**Comment by SoDa-GitHub** [comment]
@xcxnig 呃，我crontab的dailyjob没写-n。

**Comment by SoDa-GitHub** [comment]
@xcxnig 那我是不是应该再加上-n试试。。。。

**Comment by xcxnig** [comment]
@SoDa-GitHub 手动执行 结果发上来

**Comment by SoDa-GitHub** [comment]
@xcxnig 加上-n之后果然成功备份，感谢大大帮助
