### ISSUE TITLE
原版魔改版的数据库和该版有区别吗？

### ISSUE THREAD

**Issue by SoDa-GitHub** [NimaQu/ss-panel-v3-mod_Uim#110]
我打算全新安装一个ss-panel-v3-mod_Uim，然后把原版魔改版的数据库通过sql文件导入ss-panel-v3-mod_Uim。
我比对了一下两个面板的glzjin_all.sql文件，发现几乎完全一样，是不是代表着两个面板的数据库结构完全相同/向上兼容？

因为我看wiki里似乎没有提及有关数据库的注意事项
https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E4%BB%8E%E5%8E%9F%E7%89%88%E9%AD%94%E6%94%B9%E5%8D%87%E7%BA%A7

请问我这样做有可行吗？有什么需要注意的地方吗？

**Comment by NimaQu** [comment]
@SoDa-GitHub 是的
