### ISSUE TITLE
百度API临时更换为联图API方法

### ISSUE THREAD

**Issue by tokyohost** [NimaQu/ss-panel-v3-mod_Uim#112]
修改/你的站点目录/vendor/alipay-f2fpay/f2fpay/service/AlipayTradeService.php
中310行 为 $image = '<a href= "'.$content.'" target="_blank"><img src="http://qr.liantu.com/api.php?&bg=ffffff&fg=000000&text='.$size.'&text='.$url.'"  widht="'.$size.'" height="'.$size.'" />';
即可

**Comment by tokyohost** [comment]
修改/你的站点目录/vendor/alipay-f2fpay/f2fpay/service/AlipayTradeService.php
中310行 为 $image = '<a href= "'.$content.'" target="_blank"><img src="http://qr.liantu.c@om/api.php?&bg=ffffff&fg=000000&text='.$size.'&text='.$url.'"  widht="'.$size.'" height="'.$size.'" />';
即可（去掉@）

**Comment by NimaQu** [comment]
已经不需要了
