### ISSUE TITLE
Paypal支付？

### ISSUE THREAD

**Issue by YihanH** [NimaQu/ss-panel-v3-mod_Uim#116]
考慮到有些機場面向的不光光是大陸客戶，單單各類國内第三方支付感覺不太足夠。
看了下似乎pp官方是有現成的php sdk提供的 https://github.com/paypal/PayPal-PHP-SDK 
不知道是否有意向添加？

**Comment by NimaQu** [comment]
@YihanH paypal 一时爽，争议火葬场

**Comment by YihanH** [comment]
加個檢測到爭議立刻刪賬戶的功能啊（

**Comment by ZJY2003** [comment]
等到这个暑假我可以咕咕咕一个出来。

**Comment by NimaQu** [comment]
@ZJY2003 其实 Stripe 更好

**Comment by ZJY2003** [comment]
@NimaQu 一键apple pay

**Comment by NimaQu** [comment]
@ZJY2003 Google Pay 天下第一
