### ISSUE TITLE
当面付扫码提示信息被篡改

### ISSUE THREAD

**Issue by mokanet** [NimaQu/ss-panel-v3-mod_Uim#120]
密钥这些没有错误，之前也一直用当面付收款的
![2317da2d-ab9a-4081-a0ac-a0bdf8ad8dec](https://user-images.githubusercontent.com/40301835/41478958-2f4c1a7c-70fc-11e8-9ebc-c15104e3049c.jpeg)

**Comment by NimaQu** [comment]
@mokanet 多试试呢？

**Comment by mokanet** [comment]
试了很多次，几个小时了

**Comment by NimaQu** [comment]
@mokanet 无法复现
