### ISSUE TITLE
Performance issue with font css file link

### ISSUE THREAD

**Issue by WHU-KiDD** [NimaQu/ss-panel-v3-mod_Uim#121]
The style sheet files below seems is hosted on an unstable server, which may cause the web page taking more than 2min to load.
```
<link href="https://fonts.loli.net/css?family=Roboto:300,300italic,400,400italic,500,500italic" rel="stylesheet">
<link href="https://fonts.loli.net/css?family=Material+Icons">
```

By "unstable", I mean error code 500 seems to happen a lot.
BTW, after delete those code, there seems to be no problem on web page rendering.

**Comment by NimaQu** [comment]
This part of the code is related to fonts and icons. You can view the commit record to localize it.

这部分代码和字体和图标有关，你可以查看 commit 记录将其本地化
