### ISSUE TITLE
VIP节点负载显示BUG修复

### ISSUE THREAD

**Issue by SoDa-GitHub** [NimaQu/ss-panel-v3-mod_Uim#123]
resources/views/material/user/node.tpl
第231行，`import_export`之前缺失一段代码：
`cloud</i></font>  <font color="#828282">负载：{$node_latestload[$prefix]}%</font> | <font color="#ff9000"><i class="icon icon-lg">`
因缺失代码，导致VIP节点的负载无法正常显示。

另，建议第28行的“免费用户节点”更名为“普通用户节点”。

**Comment by xcxnig** [comment]
@SoDa-GitHub 自己改就行了 不是bug  特意留了两种风格
