### ISSUE TITLE
如何重新启用公共邀请码功能

### ISSUE THREAD

**Issue by tanix12qly** [NimaQu/ss-panel-v3-mod_Uim#125]
在.config.php改了半天 折腾了好久 然后发现了/app/Controllers/中的AdminController.php
虽然发现了相关文件，但是作为一只小白 改代码啥的完全不会啊_(:3」∠)_
还请作者大大告知方法 谢谢٩('ω')و

**Comment by mxihan** [comment]
@tanix12qly 请自行探索 commit中有线索（滑稽

**Comment by tanix12qly** [comment]
@mxihan 大佬能详细点说吗？摸了一圈毫无头绪

**Comment by NimaQu** [comment]
@tanix12qly 那就花钱找人改

**Comment by mxihan** [comment]
@tanix12qly 你好，不能，感谢您对ss-panel-v3-mod_Uim项目开发组的理解和支持

**Comment by xcxnig** [comment]
@mxihan 记住认准群里的admin标志

**Comment by mxihan** [comment]
@xcxnig 谨防诈骗

**Comment by ForeverOpp** [comment]
的确是鸡肋功能，人多限制用户数量就行，人少手动创建就行，非得搞邀请码。
