### ISSUE TITLE
新增自定义混淆参数（以支持运营商免流）

### ISSUE THREAD

**Issue by SoDa-GitHub** [NimaQu/ss-panel-v3-mod_Uim#126]
resources/views/material/user/edit.tpl
//565行新增代码
`obfs_param: $("#obfs_param").val()`
//564行末加个逗号
//185行新增代码
`

									<div class="card-inner">
										<p>当前混淆参数：{$user->obfs_param}</p>
										<p>注意：如果需要兼容原版SS请留空！</p>
										<div class="form-group form-group-label">
											<label class="floating-label" for="obs_param">在这输入混淆参数</label>
											<input class="form-control" id="obfs_param" type="text">
										</div>
									</div>
`

app/Controllers/UserController.php
//1503行新增代码
`$user->obfs_param = $antiXss->xss_clean($obfs_param);`
//1478行新增代码
`$obfs_param = $request->getParam('obfs_param');`

resources/views/material/user/index.tpl
//238、180行新增代码
`

    <p><dt>自定义混淆参数</dt>
    <dd>{$user->obfs_param}</dd></p>

`

效果图

![1](https://user-images.githubusercontent.com/17256673/41528165-e18b5376-731b-11e8-95f9-046fcf4f193d.jpg)
![2](https://user-images.githubusercontent.com/17256673/41528179-e7cf3bda-731b-11e8-8cad-8a8778daafa5.jpg)

**这样用户只要合适地修改混淆参数即可方便地实现运营商免流**

**Comment by NimaQu** [comment]
@SoDa-GitHub 不如直接提交 pr ？
