### ISSUE TITLE
流量使用情況圖表統計問題

### ISSUE THREAD

**Issue by masker9524** [NimaQu/ss-panel-v3-mod_Uim#134]
根据 user/trafficlog 页面显示近24小时几乎是没有流量的，但是user/index 右下方的流量使用情况图表的「今日流量」却高达2.17 GB（如附圖），不知道是不是大佬们更动到相关的统计代码？
谢谢！ ！

<img width="1412" alt="screen shot 2018-06-21 at 9 25 40 pm" src="https://user-images.githubusercontent.com/8372547/41721969-db5b300e-7599-11e8-8c69-96b289737942.png">

**Comment by xcxnig** [comment]
@masker9524 trafficlog只显示部分

**Comment by masker9524** [comment]
@xcxnig 我知道部分节点会有不支持的情况，但我今天是刻意不使用一整天，所以这个疑虑应该可以排除

**Comment by xcxnig** [comment]
@masker9524 流量记录只显示部分较大流量。

**Comment by masker9524** [comment]
@xcxnig 了解你的意思，但是已经确认过期间都没有任何连接了

**Comment by SoDa-GitHub** [comment]
两天过去了，这两天流量使用情况正常吗？

**Comment by masker9524** [comment]
@SoDa-GitHub 圖表bug還是存在，從0點到現在都沒使用，但是圖表上今日流量卻有2.多GB
這幾天直接進mysql看看哪裡出問題好了，從數字上看起來“今日流量”像是一直累加上去沒有重置

**Comment by SoDa-GitHub** [comment]
你crontab怎么写的，全都发上来看看

**Comment by masker9524** [comment]
30 22 * * * php /var/www/ssp2/xcat sendDiaryMail
0 0 * * * php -n /var/www/ssp2/xcat dailyjob
*/1 * * * * php /var/www/ssp2/xcat checkjob
*/1 * * * * php /var/www/ssp2/xcat syncnode
*/1 * * * * php /var/www/ssp2/xcat synclogin
*/1 * * * * php /var/www/ssp2/xcat syncvpn
*/1 * * * * php -n /var/www/ssp2/xcat syncnas

**Comment by SoDa-GitHub** [comment]
你能收到每日流量邮件吗？

**Comment by masker9524** [comment]
郵件是正常可收到的

**Comment by SoDa-GitHub** [comment]
手动执行
php -n /var/www/ssp2/xcat dailyjob
会输出什么？

**Comment by masker9524** [comment]
$ php -n /var/www/ssp2/xcat dailyjob

Fatal error: Interface 'JsonSerializable' not found in /var/www/ssp2/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 15

**Comment by ZJY2003** [comment]
@masker9524 composer安装了？

**Comment by ZJY2003** [comment]
@masker9524 api填对了？

**Comment by ZJY2003** [comment]
@masker9524 钱交够了？

**Comment by masker9524** [comment]
@ZJY2003 
composer回報Nothing to install or update
API?? .config.php檢查過沒錯誤

**Comment by SoDa-GitHub** [comment]
【1】确认你的php版本是否大于5.4
【2】 Php info Settings里启用json（这一步请自行google
其实你看到error log之后就已经可以自行google了

**Comment by masker9524** [comment]
感謝大佬們指路，google大致看到的不是php版本過舊就是沒安裝-json
原本環境是php7.1，剛剛直接升到php7.2.7
php info page 也標示 json support: enabled
apt-get install --reinstall php7.2-fpm php7.2-json 指令下過 問題依舊
會再找看看有沒有其他可參考網站

<img width="1003" alt="screen shot 2018-06-25 at 7 39 17 pm" src="https://user-images.githubusercontent.com/8372547/41848299-9792d2b4-78af-11e8-8e11-12c2c204558d.png">

**Comment by masker9524** [comment]
補充：嘗試執行 php /var/www/ssp2/xcat dailyjob 就成功解決了＝＝
雖然改出現以下錯誤：
PHP Warning:  file_get_contents(/var/www/ssp2/storage/qqwry.md5): failed to open stream: No such file or directory in /var/www/ssp2/app/Command/Job.php on line 229
From https://github.com/xcxnig/ssr-download
 * branch            HEAD       -> FETCH_HEAD
Already up-to-date.

**Comment by SoDa-GitHub** [comment]
这个应该是你安装前端时没有执行
`php xcat initQQWry`
导致的。
