### ISSUE TITLE
自动更新节点IP问题

### ISSUE THREAD

**Issue by jmireles7** [NimaQu/ss-panel-v3-mod_Uim#142]
最近墙的有点多，更换IP中发现有时候面板不会自动更新IP，DNS已经解析生效，手动编辑节点时尝试把IP放空保存，发现依然是之前的IP，怀疑是有缓存的可能，编辑一个乱写的IP保存，再次编辑删空IP尝试自动获取，保存后发现IP依然是那个乱写的IP，这应该能排除本机DNS缓存的可能。
怀疑gethostbyname阻塞，放了一个单单输出gethostbyname的php页面，又发现IP获取正常…
这个问题并不是时时都存在，有的时候是正常的，有的时候就挂了，而且发现有时候A节点正常更新，B节点就不行…
实在找不出原因，请大佬解惑。

**Comment by NimaQu** [comment]
@jmireles7 没遇到过...

**Comment by xcxnig** [comment]
@NimaQu 这恰恰说明是dns缓存

**Comment by SoDa-GitHub** [comment]
[https://github.com/NimaQu/ss-panel-v3-mod_Uim/pull/144/commits/5f172c61afeca2e2b5d8f2603670462bdd1bbe80](url)
BUG已修复。

**Comment by jmireles7** [comment]
@NimaQu     @SoDa-GitHub     问题依然存在，我新建了个域名一样的节点，发现新节点IP会更新，两个节点不一样的参数只有节点类型，目测是因为节点类型的问题，节点类型为“中转模式”时不更新。

**Comment by SoDa-GitHub** [comment]
你更新了dev的最新分支吗？master分支没有修复此BUG。另，dev分支经测试，中转模式也是可以更新的。
