### ISSUE TITLE
关于邀请

### ISSUE THREAD

**Issue by ppllpig** [NimaQu/ss-panel-v3-mod_Uim#148]
1.此项目为前端，不解决任何后端相关问题
2.提问前请先阅读 wiki,否则将会 close 并 block

已看WIKI，无类似问答

如果开启邀请码，后台并不会生成，而邀请链接形式有的时候太麻烦了
建议生成付费邀请码
谢谢，打扰

**Comment by NimaQu** [comment]
没有改回去的打算，请自行解决

**Comment by SoDa-GitHub** [comment]
如果你是需要【用户付费购买邀请码】功能，可以试试这个
https://github.com/SoDa-GitHub/ss-panel-v3-mod_Uim

**Comment by xcxnig** [comment]
@ppllpig 如有必要请联系开发组进行付费定制
