### ISSUE TITLE
请教新版国旗图标怎么设置？

### ISSUE THREAD

**Issue by MAOGE2018** [NimaQu/ss-panel-v3-mod_Uim#149]
//国旗图标显示
$System_Config['enable_flag']='true';    //启用该项之前务必先仔细阅读教程
$System_Config['flag_regex']='/.*(?=\s)/';    //从站点全名中匹配国家/地区的正则表达式(php版)

目前没有发现教程，之前老版本是直接办国旗名字改成线路名字就行，现在不知道如何设置！

**Comment by ahsun4** [comment]
普通节点的国旗代码是错的，把vip节点的国旗代码复制过去！，wiki里魔改常见问题里有国旗方法

**Comment by MAOGE2018** [comment]
感谢 ahsun4回复
常见问题的确有 [链接](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E9%AD%94%E6%94%B9%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)
配置节点国旗
默认节点命名规则：
国家/地区的名字+一个空格
例：
美国 A节点 //自动显示 美国.jpg
中国 深圳vps //自动显示 中国.jpg
英国 balabala //自动显示 英国.jpg
以上规则适用
但是下面的 好像失效了！
目前只支持15个常用国家/地区，如果有其他国家/地区需求，把对应的国旗图标（jpg文件）扔进public/images/prefix里即可一劳永逸。
也就是说，把节点名称改成节点名字匹配的名字是无法显示国旗的。
默认节点命名规则：国家/地区的名字+一个空格 这样依然好用。

**Comment by SoDa-GitHub** [comment]
说实话，我来回读了几遍没读懂你在说什么。可能是因为我太傻逼了。

**Comment by JarvanDing** [comment]
- - 研究了半天，原来是普通节点旗子代码没改， VIP节点才可以用！ 先去研究研究

**Comment by JarvanDing** [comment]
找到了， user/node.tpl  第44行  图片路径 修改为/images/prefix/{$node_prefix_file[$prefix]}.jpg
