### ISSUE TITLE
无法加载cdn资源

### ISSUE THREAD

**Issue by jitingcn** [NimaQu/ss-panel-v3-mod_Uim#151]
### console information
```
Refused to apply style from 'https://cdn.jsdelivr.net/gh/sspuic/p@0x03/public/theme/material/css/material.min.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

GET https://cdn.jsdelivr.net/gh/sspuic/p@0x01/public/theme/material/js/base.min.js 403 ()
node:1 Refused to execute script from 'https://cdn.jsdelivr.net/gh/sspuic/p@0x01/public/theme/material/js/base.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

GET https://cdn.jsdelivr.net/gh/sspuic/p@0x03/public/theme/material/css/fonts/MaterialIcons-Regular.woff2?v=2.2.0 403 ()

user:1 GET https://cdn.jsdelivr.net/gh/sspuic/p@0x03/public/theme/material/css/fonts/MaterialIcons-Regular.woff?v=2.2.0 403 ()
```

确认版本为最新版
尝试直接访问地址 `https://cdn.jsdelivr.net/gh/sspuic/p@0x01/public/theme/material/js/base.min.js`
返回 `User sspuic is blacklisted.`

奇怪的是刚才在我的Android手机上却能正确加载,没有页面显示问题 (猜测可能是缓存),但前天测试时却无法正常显示.
另多个用户遇到相同情况

**Comment by jitingcn** [comment]
请问这是临时解决方案么 (
或许我可以patch一下然后pr (

**Comment by NimaQu** [comment]
随意 （ 
沉迷 GTAV 懒得去改了

**Comment by jitingcn** [comment]
#152

**Comment by jitingcn** [comment]
现在两个地址
`
https://cdn.jsdelivr.net/gh/sspuic/p@0x01/public/theme/material/js/base.min.js
https://cdn.jsdelivr.net/gh/ssplb/p@0x01/public/theme/material/js/base.min.js
`
又都能正常访问了(
间歇性故障?

**Comment by NimaQu** [comment]
emmmmmmmmmmmmm 我问问 neoFelhz

**Comment by jitingcn** [comment]
测试方式： curl +
https://cdn.jsdelivr.net/gh/ssplb/p@0x04/public/assets/css/noscript.css
https://cdn.jsdelivr.net/gh/sspuic/p@0x04/public/assets/css/noscript.css
文件内容
```
/*
	Dimension by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
*/

/* Main */

	#main article {
		opacity: 1;
		margin: 4rem 0 0 0;
	}
```
错误提示 `User ssplb is blacklisted.`
间歇性抽风，且与地域有关（
当前18:40 Friday, 29 June 2018 (UTC) 情况：
欧洲地区(UK,FR) 均报错
日本sspuic可访问，ssplb报错
LAX 均报错
大陆阿里云 sspuic可访问，ssplb报错
其他地区未进一步测试 （
感觉用这个cdn还不如直接本地加载（

**Comment by TBQin** [comment]
两个CDN都挂了，请问能改成本地然后patch一下然后pr  麻烦大佬们了

**Comment by SoDa-GitHub** [comment]
面板自带本地js，临时解决办法：
类似
`https://cdn.jsdelivr.net/gh/ssplb/p@0x04/public/assets/css/noscript.css`
的链接都改为
`/assets/css/noscript.css`

**Comment by NimaQu** [comment]
@TBQin 已经修复，请更新版本
