### ISSUE TITLE
无法根据用户邮箱获取头像

### ISSUE THREAD

**Issue by ForeverOpp** [NimaQu/ss-panel-v3-mod_Uim#154]
![image](https://user-images.githubusercontent.com/9302540/42087528-06c1e3de-7bc9-11e8-9b70-6737c54b3cfd.png)

如图，使用原魔改版正常，此版本不正常。

**Comment by NimaQu** [comment]
@ForeverOpp 用 gravatar 的太少了，所以删掉了这个功能

**Comment by ForeverOpp** [comment]
那如何开启？是否可以通过修改部分文件解决？

**Comment by NimaQu** [comment]
@ForeverOpp 可以

**Comment by ForeverOpp** [comment]
希望可以给一个文件名，如果不能我就自己对照commit以及原版文件寻找改动去了。

**Comment by NimaQu** [comment]
@ForeverOpp UserController
