### ISSUE TITLE
F:请问如何启用该版本sspanel节点添加中的混淆/加密

### ISSUE THREAD

**Issue by sht2017** [NimaQu/ss-panel-v3-mod_Uim#156]
萌新一枚ヾ(´A｀)ノﾟ
关于上述问题参照了诸多版本/镜像
得出的普遍解决方案是修改/resources/views/material/user/edit.tpl以解决该问题
但该版本中edit.tpl与原版相同，无需修改
而网站中仍无关于自定义加密/混淆的相关选项
望予以告知，谢谢

**Comment by NimaQu** [comment]
![image](https://user-images.githubusercontent.com/26685881/42093374-aecbff78-7bde-11e8-85a2-5e3dccd76443.png)
是你瞎了还是我幻视了？
