### ISSUE TITLE
建議增加商品列表智能排序

### ISSUE THREAD

**Issue by YihanH** [NimaQu/ss-panel-v3-mod_Uim#180]
目前默認商品列表頁是無排序狀態，添加商品的類別順序不一樣就會看著很奇怪= =
建議為商品添加 sort_id 字段進行排序或是直接套用節點列表的排序規則

**Comment by xcxnig** [comment]
@YihanH 建议很好，写一个提交吧

**Comment by Possible964** [comment]
@YihanH 建议很好，写一个提交吧

**Comment by wewall** [comment]
@YihanH 实现思路添加seqNo列, 写好提交吧, 这个很简单

**Comment by ZJY2003** [comment]
@wewall 围墙赶快给我写PHP队列啊

**Comment by SoDa-GitHub** [comment]
最新版本中商品名已根据商品名排序。

**Comment by wewall** [comment]
@ZJY2003 我是猪 啥都不会

**Comment by NimaQu** [comment]
@wewall 你是绒布球

**Comment by wewall** [comment]
换了个头像, 感觉自己又可爱了很多呢
