### ISSUE TITLE
[重要]公用账户被CDN站点加入黑名单

### ISSUE THREAD

**Issue by ForeverOpp** [NimaQu/ss-panel-v3-mod_Uim#181]
前端所用CSS、JS，凡是来自https://cdn.jsdelivr.net/gh/sspuic/p@0x03/public/theme/material/css/base.min.css
即https://cdn.jsdelivr.net/都无法使用，表现为站点混乱，按钮无法点击，如图：
![image](https://user-images.githubusercontent.com/9302540/42268230-91b860f2-7fad-11e8-9736-3765ac719a7a.png)
访问CDN出现如下提示：
![image](https://user-images.githubusercontent.com/9302540/42268181-7056ba62-7fad-11e8-8ed1-6bc330dc64e3.png)

**Comment by ForeverOpp** [comment]
推荐解决办法：
进入网站文件夹，比如/www/wwwroot/xxx.com/
输入以下命令：
```shell
find | grep .tpl | xargs perl -pi -e 's|sspuic\/p\@0x[0-9][0-9]|NimaQu\/ss-panel-v3-mod_Uim|g'
```
然后，键入：
```shell
find | grep .tpl | xargs perl -pi -e 's|https:\/\/cdn.jsdelivr.net\/gh\/NimaQu\/ss-panel-v3-mod_Uim\/public\/theme\/material\/js\/jquery.min.js|https:\/\/cdn.bootcss.com\/jquery\/3.3.1\/jquery.min.js|g'
```
即可。

**Comment by NimaQu** [comment]
@ForeverOpp 说的好，然而早就修了

**Comment by ForeverOpp** [comment]
不存在的，还是那样，甚至ssplb也不行，用你这个最稳。

On Jul 4, 2018 18:51, NimaQu <notifications@github.com> wrote:

@ForeverOpp<https://github.com/ForeverOpp> 说的好，然而早就修了

**Comment by NimaQu** [comment]
@ForeverOpp https://github.com/NimaQu/ss-panel-v3-mod_Uim/commit/92f1f60c1508f4c091293c0aad03f773a2ab3662

**Comment by ForeverOpp** [comment]
怪我怪我，我还查了一波命令，忘了直接git pull升级一下了

On Jul 4, 2018 19:02, NimaQu <notifications@github.com> wrote:

@ForeverOpp<https://github.com/ForeverOpp> 92f1f60<https://github.com/NimaQu/ss-panel-v3-mod_Uim/commit/92f1f60c1508f4c091293c0aad03f773a2ab3662>
