### ISSUE TITLE
windows端订阅失败

### ISSUE THREAD

**Issue by zwt12370** [NimaQu/ss-panel-v3-mod_Uim#192]
已设置cloudflare的页面规则，android端可以正常订阅，win端订阅失败。尝试复现：win端和android端同时订阅喵帕斯和该面板的链接,android端均订阅成功,windows端订阅喵帕斯的成功，订阅该面板的失败。多次复现均出现该问题

**Comment by NimaQu** [comment]
@zwt12370 https://docs.rixcloud.us/API/TLS-issue/

**Comment by dalekzhangdong** [comment]
怎么解决的
