### ISSUE TITLE
关于商品下架后自动续费的问题

### ISSUE THREAD

**Issue by lenovoy450** [NimaQu/ss-panel-v3-mod_Uim#194]
已在demo.nimaqu.com上测试。
如果是操作失误导致，请大佬们多包涵，并指出错误，感谢不尽。
具体情形为下架原有自动续费商品，用户购买记录中，续费时间会变成不自动续费。
商品上架、正常购买时
![admin-shop](https://user-images.githubusercontent.com/24227226/42729706-73138eb0-8813-11e8-853e-8ddae1f7cbdf.jpg)
![user-bought](https://user-images.githubusercontent.com/24227226/42729710-78f5320c-8813-11e8-80b3-18cbc38b2870.jpg)
商品下架后
![admin-shop-2](https://user-images.githubusercontent.com/24227226/42729714-8bb74e5c-8813-11e8-9cf8-ea503eeb520f.jpg)
![user-bought-2](https://user-images.githubusercontent.com/24227226/42729716-918f284a-8813-11e8-87f0-602916592521.jpg)

**Comment by SoDa-GitHub** [comment]
@lenovoy450 ？？？不特么就应该这样么？咋的？你还想下架商品后用户还能继续购买？

**Comment by lenovoy450** [comment]
但是，这个问题发生在上周，之前，同样的代码，不是这个逻辑. 也就是下架了，购买记录里面还是有自动续费. 从魔改开始就有这个问题，我用了一年多，我看代码没有变化.
代码的逻辑应该就是这样才正确，这才是让我觉得奇怪的地方. 现在我没法复现下架了，还能续费。无论是魔改还是魔改修改版。 但是，去看购买记录。在前天之前，所有被下架的套餐的自动续费都在. 
真是抱歉，没有把前提说清楚，包括您去看群讨论，也能发现在此之前，是存在可以续费的. 我去找找. 所以，这才是我觉得奇怪的地方. 是什么触发真正的代码逻辑呢.

**Comment by NimaQu** [comment]
刚刚测试了下，确实是这样
