### ISSUE TITLE
关于新建节点

### ISSUE THREAD

**Issue by alienyan** [NimaQu/ss-panel-v3-mod_Uim#195]
为什么没办法新建节点，就是在新建节点那个页面填完了信息然后点击添加后却没有添加节点...

**Comment by mxihan** [comment]
@alienyan 请自行排查，重点排查tg机器人相关

**Comment by alienyan** [comment]
@mxihan 可是我都没有开啊

**Comment by mxihan** [comment]
@alienyan 已确认是bug，开发组内正在进行git blame（滑稽

**Comment by alienyan** [comment]
@mxihan emmm看来只能从数据库加...

**Comment by SoDa-GitHub** [comment]
可否提供ssh以供debug？

**Comment by alienyan** [comment]
@SoDa-GitHub 可以，发到你邮箱吗

**Comment by SoDa-GitHub** [comment]
soda_mail@qq.com

**Comment by alienyan** [comment]
@SoDa-GitHub 搞定了说一声
