### ISSUE TITLE
IOS小火箭批量SS://添加失败

### ISSUE THREAD

**Issue by jmireles7** [NimaQu/ss-panel-v3-mod_Uim#200]
因为加密改了AEAD，所以订阅链接失效，点击用户中心的SS://批量链接导入后，发现只导入一个节点！
在NimaQu大佬Demo站点测试，依然只导入一个节点，相信不是我自己面板的问题。
小火箭为美区2.1.21版。

另外有个小提议，用户改了AEAD并不需要取消订阅链接获取，当初这个设置可能是考虑到改了AEAD后SSR客户端再订阅会有加密不支持的问题，然而，相信改了AEAD还不知道换SS客户端的毕竟少数，而小火箭对AEAD也是支持的，订阅不成问题。

**Comment by wewall** [comment]
你有没有想过，试过很多站点都不能导入是你自己的手机问题

**Comment by jmireles7** [comment]
@wewall   这么说大佬测试过了没有问题？

**Comment by wewall** [comment]
@jmireles7 我觉得你可以贴出来你的ss批量地址, 以供测试 (请使用虚假数据测试)

**Comment by SoDa-GitHub** [comment]
是不是你同时使用了AEAD＋混淆

**Comment by SoDa-GitHub** [comment]
https://github.com/NimaQu/ss-panel-v3-mod_Uim/pull/235
