### ISSUE TITLE
购买商品重置流量问题

### ISSUE THREAD

**Issue by number018** [NimaQu/ss-panel-v3-mod_Uim#201]
config中设置   购买时重置流量   为false时：

- 1.商品设置false，加流量不加时间---没毛病

- 2.商品设置true，加流量不加时间---有毛病，也加了流量，应该重置吧？

-----

config中设置   购买时重置流量   为true时：

- 1.商品设置false，流量重置时间重置---有毛病，流量应该不重置才对吧？

- 2.商品设置true，流量重置时间重置---没毛病

-----
以上为手动续费的测试结果

我不太懂这一部分的逻辑是怎么安排的。
之前的版本中，逻辑不是挺好嘛？   （因为之前没问题）
config中false，商品false---不重置 ；商品true---重置
config中true，商品false---不重置 ；商品true---重置

还有询问一下，现在版本的商品时间  全都以 购买时间  来计算？    已测试重复购买商品不可叠加时间。

**Comment by SoDa-GitHub** [comment]
@number018 商品里那个true和false是指的哪个？【续费时自动重置用户流量为上面这个流量值】？

**Comment by number018** [comment]
指的时 流量 一栏  续费时自动重置用户流量为上面这个流量值 前面的按钮

**Comment by number018** [comment]
对的，是这个

**Comment by SoDa-GitHub** [comment]
@number018 旧版本的逻辑有空子可以钻，低等级和高等级的搀着买的话，可以用更少的钱获得更多的流量，同时还能以低成本保持自己的高等级

**Comment by number018** [comment]
那现在就是唔，按照这个逻辑来的话，确实，我上次也测试出了，不过不是更少钱得更多流量，是时间的问题。
所以综上
目前就统一以config里设置true，不管商品true/false   都重置流量和时间
config为false，不管商品true/false  都不重置流量 但是不重置时间---ps：时间不管如何都会重置

是这么个逻辑了吧

**Comment by SoDa-GitHub** [comment]
@number018 你可以这么理解。其实这个改动对一般用户影响也不大的吧，用完了继续再买/开启自动续订，效果和之前还是一样的

**Comment by number018** [comment]
ok，哭笑不得- -，我一开始也没想到会这样。
我...绝大部分客户...会自己手动续费，前天一客户问我为啥时间少了10天...昨天一客户问我为啥重复购买（搞优惠想多买几个月），时间没加...我就突然感觉不对劲- -

**Comment by SoDa-GitHub** [comment]
@number018 我本人是希望这个面板可以帮助站长完成以下两点：
【1】让用户默默地浪费掉更多的流量。（比如用户买了6个30G的月卡，通常每个月月底都会剩余1～2G浪费掉，半年下来每个用户就能浪费6～12G流量，用户很多的话，这个浪费的的流量会很可观。但是如果流量和时间允许叠加，本来半年有6次清空流量的机会，立刻变成半年只能清空一次，用户半年才会浪费1～2G流量）
【2】诱导用户购买更高级、时间更长的套餐（套餐时长无法叠加后，用户为了避免【1】中的浪费，便会去购买季卡、年卡等更高价、更高级、时间也更长的套餐，某种程度上默默带动了用户的消费能力）

**Comment by number018** [comment]
@SoDa-GitHub 哈哈哈，黑心机场#滑稽，你pull的购买邀请码，其实我也写过，哈哈哈，我居然没想到你居然更黑心的重置端口都写了,可恶啊，hasaki
