### ISSUE TITLE
管理员主面板的流量显示错误

### ISSUE THREAD

**Issue by WTFTWTM** [NimaQu/ss-panel-v3-mod_Uim#202]
大概就是，，，那个流量使用情况那个显示，已使用流量和今日使用流量，写反了。
虽然不是啥问题，但是可以的话就改一下吧，然后发现项目有很多杂余文件，可否优化？

**Comment by Insightfy** [comment]
你都说了不是啥问题了，自己改一下不就行了，倒一下参数而已。

**Comment by SoDa-GitHub** [comment]
@Insightfy bug再小也是bug

**Comment by NimaQu** [comment]
无图言屌...

**Comment by wewall** [comment]
无异常

**Comment by SoDa-GitHub** [comment]
dev站确实复现这个bug了

**Comment by WTFTWTM** [comment]
![image](https://user-images.githubusercontent.com/34577787/43675883-1028448c-981a-11e8-809e-a5be21ae3fcf.png)

**Comment by NimaQu** [comment]
magic..

**Comment by SoDa-GitHub** [comment]
问题已查明，那个“已使用的流量”实际上表示“除了今天，过去已使用的流量”，因此真正的已用是“已使用+今日使用”
