### ISSUE TITLE
自动设置 Crisp 的邮箱

### ISSUE THREAD

**Issue by maxitio** [NimaQu/ss-panel-v3-mod_Uim#206]
在 main.tpl 的 Crisp 代码下面加一行
`$crisp.push(["set", "user:email", "{$user->email}"]);`
就可以自动设置用户的邮箱，用户点开 Crisp 对话框后就不用再输入邮箱了。
除了自动设置邮箱外，还可以推送很多数据到 Crisp 上，比如说用户等级什么的，可以更方便地让客服或管理员解决用户的问题。
 Crisp 官方文档：https://help.crisp.chat/en/article/how-to-use-dollarcrisp-javascript-sdk-10ud15y/

**Comment by NimaQu** [comment]
@maxitio 来个 pr？

**Comment by YihanH** [comment]
@NimaQu 你要的pr https://github.com/NimaQu/ss-panel-v3-mod_Uim/pull/209
