### ISSUE TITLE
Macbook访问后台能耗很高

### ISSUE THREAD

**Issue by pkyiao16** [NimaQu/ss-panel-v3-mod_Uim#212]
使用Macbook访问后台的时候风扇一直在叫，CPU占用很高，怀疑是Canvas动画的原因，是否可以优化一下？

**Comment by SoDa-GitHub** [comment]
对不起，开发组很穷所以买不起macbook，所以也无法复现并debug此问题。

**Comment by galaxychuck** [comment]
@SoDa-GitHub 对不起，开发组很穷所以买不起macbook，所以也无法复现并debug此问题。

**Comment by wewall** [comment]
@pkyiao16 你这个问题是由于粒子特效产生的, 请关闭站点粒子特效, 以便节能

**Comment by pkyiao16** [comment]
@wewall 我不是很懂前端这块, 麻烦请问一下如何关闭这个特效

**Comment by galaxychuck** [comment]
@pkyiao16 resources/views/material/footer.tpl
resources/views/material/user/footer.tpl
注釋掉<script type="text/javascript" color="217,113,24" opacity="0.8" count="150" src="/assets/js/canvas-nest.min.js"></script>

**Comment by pkyiao16** [comment]
@galaxychuck 非常感谢, 耗能已经下来了
