### ISSUE TITLE
google兩步驟登入驗證輸入

### ISSUE THREAD

**Issue by tim1014** [NimaQu/ss-panel-v3-mod_Uim#214]
在登入頁面加以下代碼，密碼輸入下面 (不懂得怎樣 git pull，直接發了 :3)：

												<div class="form-group form-group-label">
													<div class="row">
														<div class="col-md-10 col-md-push-1">
															<label class="floating-label" for="code">GA 两步骤验证 (没设定请留空)</label>
															<input class="form-control" id="code" type="text" placeholder="没设定请留空">
														</div>
													</div>
												</div>

**Comment by NimaQu** [comment]
这个 GA 因为用的人实在太少所以去掉了
