### ISSUE TITLE
sspanel 的对接部分源码是哪些

### ISSUE THREAD

**Issue by mayday12138** [NimaQu/ss-panel-v3-mod_Uim#215]
我想自己测试一下能不能更改一下spanel的对接源码来实现跟sspanel v4版本的后端对接，因为sspanel v4的后端支持v2ray和ssr，并且支持v2ray的流量统计

**Comment by SoDa-GitHub** [comment]
@mayday12138 大神，我看好你

**Comment by anisipng** [comment]
@mayday12138 大佬，看好你

**Comment by NimaQu** [comment]
应该在 LinkController.php ，坐等大佬 pr

**Comment by cangshuking** [comment]
如果是webapi的话，应该是在\app\Controllers\Mod_Mu这个文件夹里的
