### ISSUE TITLE
能否将节点连接状态改为TCP判断？

### ISSUE THREAD

**Issue by anisipng** [NimaQu/ss-panel-v3-mod_Uim#216]
目前TCP阻断实在是太频繁了，但是现在项目的节点连接状态好像是根据对接来判断是否正常，我想能不能加个被墙判断？毕竟现在被墙发邮件已经有了（虽然不够完善，我四个节点被墙，只提醒一个）

**Comment by SoDa-GitHub** [comment]
节点状态那个之前设计失误，只留了掉线/在线两个状态，如果要再塞一个可能要大改。这个问题正在考虑中。

**Comment by lhie1** [comment]
可以参考一下胖虎dalao的 https://raw.githubusercontent.com/ssrpanel/SSRPanel/f04c7da893141055b537ae481890b77c96732d03/app/Console/Commands/AutoCheckNodeStatus.php

**Comment by SoDa-GitHub** [comment]
@lhie1 有个P好参考的，这么简单的逻辑当然会写，又不是白痴。都说了是设计失误。翻译一下“设计失误”：如果想实现这个功能，得推倒前面很多的代码重新改写，能理解？

**Comment by NimaQu** [comment]
等一个重写面板的

**Comment by anisipng** [comment]
@SoDa-GitHub 想想确实是设计失误，之前没想过会有TCP阻断这么狠，代码我看过了，推倒重建确实很麻烦的，等待有大佬解决这个问题
