### ISSUE TITLE
面板生成的Surge配置文件无法导入

### ISSUE THREAD

**Issue by maxitio** [NimaQu/ss-panel-v3-mod_Uim#220]
Surge错误提示
![jietu20180803-182955](https://user-images.githubusercontent.com/18343067/43638570-f35f1cd2-974b-11e8-8747-24c501fe75b4.jpg)

生成的配置文件错误的地方
`node = custom,balabala.com,1234,chacha20,password,http://omgib13x8.bkt.clouddn.com/SSEncrypt.module,,obfs=http,obfs-host=wns.windows.com,udp-relay=true,tfo=true
`

应该是 LinkController.php 里的这行写多了个逗号吧。
` $proxy_group .= $item['remark'].' = custom,'.$item['address'].','.$item['port'].','.$item['method'].','.$item['passwd'].',http://omgib13x8.bkt.clouddn.com/SSEncrypt.module,'.URL::getSurgeObfs($item).',obfs-host=wns.windows.com,udp-relay=true,tfo=true'."\n";
`

**Comment by wewall** [comment]
没有 Surge 账户, 无法重现 BUG

**Comment by maxitio** [comment]
@wewall Surge for Mac 和 Surge for iOS 都可以免费下载试用，试用时也可以导入配置文件。。

**Comment by SoDa-GitHub** [comment]
URL::getSurgeObfs里多了个逗号

**Comment by lwsg1987** [comment]
是的 多逗号 
有大神用户提醒我了

自己删除一个就可以

**Comment by maxitio** [comment]
@SoDa-GitHub 删除URL::getSurgeObfs里面的逗号后，当协议设置为origin，混淆为simple_obfs_http时，会无法导入。删除 `,http://omgib13x8.bkt.clouddn.com/SSEncrypt.module,` 这个里面的最后一个逗号，可以解决。

**Comment by SoDa-GitHub** [comment]
getSurgeObfs里的逗号要加判断，的确挺麻烦的，实际上我也删除的是module后面的逗号。
