### ISSUE TITLE
请问现在的tg群是啥呢？

### ISSUE THREAD

**Issue by 9527dong** [NimaQu/ss-panel-v3-mod_Uim#222]
现在的tg群怎么打不开了，为啥解散了啊

**Comment by anisipng** [comment]
@9527dong TG群就是页面显示的那个，没有解散

**Comment by 9527dong** [comment]
我现在无法加入啊，显示：sorry this group doesn't seem to exist，这是怎么回事呢 @anisipng

**Comment by wewall** [comment]
warn
