### ISSUE TITLE
Message: Class 'ExtendParams' not found

### ISSUE THREAD

**Issue by ranguisheng** [NimaQu/ss-panel-v3-mod_Uim#223]
Message: Class 'ExtendParams' not found
File: /home/ec2-user/www/fishvpn.club/app/Utils/Pay.php
Line: 286
Trace: #0 /home/ec2-user/www/fishvpn.club/app/Controllers/UserController.php(371): App\Utils\Pay::alipay_get_qrcode(Object(App\Models\User), '1', NULL)

f2fpay的时候报这个，没看出来什么原因，多谢

**Comment by SoDa-GitHub** [comment]
你肯定用的什么远古版本

**Comment by lokisama** [comment]
你好，我也碰到了。
按照教程宝塔安装
php7.0

{
    "message": "Slim Application Error",
    "error": [
        {
            "type": "Error",
            "code": 0,
            "message": "Class 'ExtendParams' not found",
            "file": "\/www\/wwwroot\/b.linkersocks.com\/app\/Utils\/Pay.php",
            "line": 286,
            "trace": [
                "#0 \/www\/wwwroot\/b.linkersocks.com\/app\/Controllers\/UserController.php(371): App\\Utils\\Pay::alipay_get_qrcode(Object(App\\Models\\User), '0.1', NULL)",
                "#1 [internal function]: App\\Controllers\\UserController->f2fpay(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#2 \/www\/wwwroot\/b.linkersocks.com\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(41): call_user_func(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#3 \/www\/wwwroot\/b.linkersocks.com\/vendor\/slim\/slim\/Slim\/Route.php(366): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#4 \/www\/wwwroot\/b.linkersocks.com\/app\/Middleware\/Auth.php(43): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#5 [internal function]: App\\Middleware\\Auth->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))",
                "#6 \/www\/wwwroot\/b.linkersocks.com\/vendor\/slim\/slim\/Slim\/DeferredCallable.php(46): call_user_func_array(Object(App\\Middleware\\Auth), Array)",
                "#7 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))",
                "#8 \/www\/wwwroot\/b.linkersocks.com\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(73): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))",
                "#9 \/www\/wwwroot\/b.linkersocks.com\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(122): Slim\\Route->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#10 \/www\/wwwroot\/b.linkersocks.com\/vendor\/slim\/slim\/Slim\/Route.php(334): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#11 \/www\/wwwroot\/b.linkersocks.com\/vendor\/slim\/slim\/Slim\/App.php(545): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#12 \/www\/wwwroot\/b.linkersocks.com\/vendor\/zeuxisoo\/slim-whoops\/src\/Zeuxisoo\/Whoops\/Provider\/Slim\/WhoopsMiddleware.php(70): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#13 [internal function]: Zeuxisoo\\Whoops\\Provider\\Slim\\WhoopsMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))",
                "#14 \/www\/wwwroot\/b.linkersocks.com\/vendor\/slim\/slim\/Slim\/DeferredCallable.php(46): call_user_func_array(Object(Zeuxisoo\\Whoops\\Provider\\Slim\\WhoopsMiddleware), Array)",
                "#15 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))",
                "#16 \/www\/wwwroot\/b.linkersocks.com\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(73): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))",
                "#17 \/www\/wwwroot\/b.linkersocks.com\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(122): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#18 \/www\/wwwroot\/b.linkersocks.com\/vendor\/slim\/slim\/Slim\/App.php(438): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#19 \/www\/wwwroot\/b.linkersocks.com\/vendor\/slim\/slim\/Slim\/App.php(370): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#20 \/www\/wwwroot\/b.linkersocks.com\/config\/routes.php(368): Slim\\App->run()",
                "#21 \/www\/wwwroot\/b.linkersocks.com\/public\/index.php(11): require('\/www\/wwwroot\/b....')",
                "#22 {main}"
            ]
        }
    ]
}

**Comment by lokisama** [comment]
你好我也碰到
宝塔安装，php7.0

{
    "message": "Slim Application Error",
    "error": [
        {
            "type": "Error",
            "code": 0,
            "message": "Class 'ExtendParams' not found",
            "line": 286,
