### ISSUE TITLE
做一个根据用户手机壳颜色或者机箱颜色自动改变网站主题色为相应颜色的功能

### ISSUE THREAD

**Issue by NimaQu** [NimaQu/ss-panel-v3-mod_Uim#224]
@wewall 立即落实

**Comment by wewall** [comment]
喵喵喵？

**Comment by NimaQu** [comment]
@wewall 立即跟进

**Comment by xcxnig** [comment]
@NimaQu 持续关注

**Comment by Roy47Zhang** [comment]
hahahah笑死

**Comment by anisipng** [comment]
噗哈哈哈。。。一脸懵逼

**Comment by mxihan** [comment]
@wewall 其实部分手机（特别是Nokia）可以根据型号/序列号等判断出颜色，所以说也不是不可以实现此功能。

**Comment by SoDa-GitHub** [comment]
@mxihan 你们是真的闲的蛋疼

**Comment by Possible964** [comment]
试试调用前置摄像头读取用户虹膜反射出来的手机壳颜色
@wewall 立即测试

**Comment by Taylor000** [comment]
虹膜反射出来的是手机还是手？是自己手上的手机还是别的手机哦

**Comment by xcxnig** [comment]
理论上需要前置2000万，照亮你的美的柔光拍照相机才行。

**Comment by JarvanDing** [comment]
你们可真是欢乐多。

**Comment by 8ylYile** [comment]
机箱颜色 我觉得不合适 倒是读取灯条或者内存条的颜色或者风扇的颜色我觉得很合适 当然我说的是光污染的机箱不是普通机箱
