### ISSUE TITLE
建议加一个屏蔽国产浏览器访问的功能

### ISSUE THREAD

**Issue by Roy47Zhang** [NimaQu/ss-panel-v3-mod_Uim#225]
比如这样行不？
通过UA关键字判定
```
//获取UA信息
$ua = $_SERVER['HTTP_USER_AGENT'];
//将USER_AGENT存入数组
$now_ua = array('360SE','The World','BIDUBrowser','Maxthon','QQBrowser','LBBROWSER','MicroMessenger','QQ/','360','TaoBrowser','MetaSr','Tencent','UCBrowser','MiuiBrowser','baiduboxapp','MQQBrowser','2345Explorer','115Browser');
if(!$ua) {
    header("Content-type: text/html; charset=utf-8");
    echo('请在使用本站时：');
    die('请勿使用国产浏览器');
}else{
    foreach($now_ua as $value )
//判断是否是数组中存在的UA
    if(eregi($value,$ua)){
        header("Content-type: text/html; charset=utf-8");
        echo('请在使用本站时：');
        die('请勿使用国产浏览器');
    }
}
```

**Comment by SoDa-GitHub** [comment]
@Roy47Zhang 感觉不错，但是百度浏览器是不是少了一个字母A

**Comment by SoDa-GitHub** [comment]
@Roy47Zhang 要不发个PR？

**Comment by Roy47Zhang** [comment]
@SoDa-GitHub BIDU这个还真没错，我自己搜集的时候也迷糊了一下，不过eregi这个函数php7里用不了，本萌新很迷茫

**Comment by Roy47Zhang** [comment]
`$userAgent = $_SERVER['HTTP_USER_AGENT'];
if(preg_match('/360SE/i',$userAgent) || preg_match('/The World/i',$userAgent) || preg_match('/BIDUBrowser/i',$userAgent) || preg_match('/Maxthon/i',$userAgent) || preg_match('/QQBrowser/i',$userAgent) || preg_match('/LBBROWSER/i',$userAgent) || preg_match('/MicroMessenger/i',$userAgent) || preg_match('/QQ/i',$userAgent) || preg_match('/360/i',$userAgent) || preg_match('/TaoBrowser/i',$userAgent) || preg_match('/MetaSr/i',$userAgent) || preg_match('/Tencent/i',$userAgent) || preg_match('/UCBrowser/i',$userAgent) || preg_match('/MiuiBrowser/i',$userAgent) || preg_match('/baiduboxapp/i',$userAgent) || preg_match('/115Browser/i',$userAgent)) 
{
        header("Content-type: text/html; charset=utf-8");
        echo("请在使用本站时：");
        die("请勿使用国产浏览器");
    }`
然后我就捣鼓出了出了这么丑的几行东西出来，这么丑的代码提交PR真的可以吗

**Comment by anisipng** [comment]
@Roy47Zhang 试了你捣鼓的这段，但是好像没用啊，不知道是哪里出问题了，用国产浏览器还是可以访问站点

**Comment by SoDa-GitHub** [comment]
经研究，此功能非常有价值，但是不幸无法实现（360等浏览器的UA里已经删去了360标识，因此无法获取并判断）。
