### ISSUE TITLE
关于ssrmu对接的一个bug反馈

### ISSUE THREAD

**Issue by shuaixr** [NimaQu/ss-panel-v3-mod_Uim#229]
在使用Wiki中的ssrmu对接的教程时发现ss-panel一直显示节点离线
便用docker logs ssrmu发现了如下错误
ERROR: Error data:{"ret":0,"data":"token or source is invalid"}
在反复查验各项配置保证都是对的，但这个错误一直存在
翻阅ss-panel的源代码后将app/Middleware/Mod_Mu.php的第44行代码修改如下
$res['data'] = "token or source is invalid". $_SERVER["REMOTE_ADDR"];
再次重新运行ssrmu发现报错如下
ERROR: Error data:{"ret":0,"data":"token or source is invalidxxx:xxx:xxx:xxx(这是一个ipv6地址)"}
我在配置节点的时候使用的是域名，让它自己解析ip
可惜并没有解析ipv6的地址导致ip校验失败
感觉ipv6在国外服务器上存在了很长时间了你们都没有出现这个bug吗...
求修复这个bug或者说如何让ssrmu使用ipv4地址进行api

**Comment by NimaQu** [comment]
@shuaixr 是的，就你出现这个 bug

**Comment by shuaixr** [comment]
@NimaQu 通过将cloudfilare的ipv6解析关闭曲线救国解决了这个bug😮

**Comment by zhoupingxiao** [comment]
> 这个不是bug，Linux系统默认在解析dns时，ipv6的优先级比ipv4要高，可以通过修改/etc/gai.conf解决。
> 方法就是移除此行`#precedence ::ffff:0:0/96 100`的注释

你好。/etc/gai.conf 这个文件在哪？我的Linux系统里没这个文件
