### ISSUE TITLE
Bug反馈，请 @NimaQu 先生立即落实

### ISSUE THREAD

**Issue by wewall** [NimaQu/ss-panel-v3-mod_Uim#237]
当在内容中含有  Emoji 时（例如：🎋），新增会 500 ， 修改会 405 
请优秀的 @NimaQu 先生立即落实此问题。

**Comment by wewall** [comment]
有🐴也会的
![image](https://user-images.githubusercontent.com/33481440/44206442-5cd8b700-a18c-11e8-9cef-4f5cfc610bb9.png)
![image](https://user-images.githubusercontent.com/33481440/44206429-56e2d600-a18c-11e8-8a03-880c05183045.png)

**Comment by NimaQu** [comment]
我记得钱爸爸测试过 emoji 没问题啊

**Comment by wewall** [comment]
@NimaQu 你现在测试试试，不是markdown Emoji是原生Emoji，MarkDown的是Pic吧，不是真正的Emoji

**Comment by wewall** [comment]
:tanabata_tree:

**Comment by wewall** [comment]
![image](https://user-images.githubusercontent.com/33481440/44345229-51a3c500-a4c5-11e8-84e5-34156b0375dd.png)

**Comment by tim1014** [comment]
@NimaQu 單端口分組訂閱不能用。在用戶資料編輯介面有代碼問題，一堆紅色字及排版問題。

**Comment by NimaQu** [comment]
@tim1014 后者 fixed 单端口分组订阅是什么？？？

**Comment by tim1014** [comment]
@NimaQu 訂閱地址後面那個 ?mu=80 ?mu=443。不太懂得怎樣表白

**Comment by wewall** [comment]
又不是不能用
