### ISSUE TITLE
关于SMTP发信sender显示的问题

### ISSUE THREAD

**Issue by Roy47Zhang** [NimaQu/ss-panel-v3-mod_Uim#238]
首先我使用的是Gmail，在Config.php中已经配置了
`$System_Config['smtp_name'] = 'Name';
$System_Config['smtp_sender'] = 'Sender';`
但是实际收信显示为
![image](https://user-images.githubusercontent.com/24809366/44295516-016a0e80-a2dd-11e8-9e03-605657de13ad.png)
接着我自己给\app\Services\Mail\Smtp.php Line22加了一行
`$mail->FromName = "Sender-Name";`
然后就正常显示了
所以这算个bug吗_(:3」∠)_

**Comment by NimaQu** [comment]
本来就这样的，默认 sender 是你的主机名

**Comment by Roy47Zhang** [comment]
哇是我孤陋寡闻了

**Comment by wewall** [comment]
@NimaQu 有的邮箱不是诶，可以自定义

**Comment by 5864048** [comment]
发信不能发，配置正确。国内的腾讯企业邮箱

**Comment by Anankke** [comment]
> 发信不能发，配置正确。国内的腾讯企业邮箱

哦

**Comment by Passipur** [comment]
@5864048 您好 这边建议您联系腾讯客服询问原因

**Comment by GregTechnology** [comment]
@Anankke 您好 这边建议您拨打110以获得客服支持

**Comment by GregTechnology** [comment]
> 发信不能发，配置正确。国内的腾讯企业邮箱

您好 这边建议您拨打110以获取客服支持

**Comment by jimmyalxe** [comment]
服务器的25端口解锁了吗？

**Comment by Anankke** [comment]
没事不要再不相关的 issue 下面发东西
