### ISSUE TITLE
adsense添加问题

### ISSUE THREAD

**Issue by bigrain1993** [NimaQu/ss-panel-v3-mod_Uim#240]
1.此项目为前端，不解决任何后端相关问题
2.提问前请先阅读 wiki,否则将会 close 并 block
由于咱们的网页文件格式是.tpl，谷歌adsense只提供了在html文件中加入广告的代码，如何在.tpl文件中潜入adsense呢？

**Comment by mayingjiejiejie** [comment]
我在php里面加的

**Comment by wewall** [comment]
照葫芦画瓢
