### ISSUE TITLE
点击邀请码报错

### ISSUE THREAD

**Issue by MichealChan** [NimaQu/ss-panel-v3-mod_Uim#250]
Whoops\Exception\ErrorException thrown with message "Undefined index: table_config"

Stacktrace:
#33 Whoops\Exception\ErrorException in /home/wwwroot/default/storage/framework/smarty/compile/f5b5fa25e7756b00cd7600dd03fedb41e0bd1c71_0.file.js_2.tpl.php:28
#32 Whoops\Run:handleError in /home/wwwroot/default/storage/framework/smarty/compile/f5b5fa25e7756b00cd7600dd03fedb41e0bd1c71_0.file.js_2.tpl.php:28
#31 content_5b876b139140c9_15958109 in /home/wwwroot/default/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:128
#30 Smarty_Template_Resource_Base:getRenderedTemplateCode in /home/wwwroot/default/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:172
#29 Smarty_Template_Compiled:render in /home/wwwroot/default/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:206
#28 Smarty_Internal_Template:render in /home/wwwroot/default/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:372
#27 Smarty_Internal_Template:_subTemplateRender in /home/wwwroot/default/storage/framework/smarty/compile/8b629bcb40442b249040cbd952357087733d2632_0.file.invite.tpl.php:262
#26 content_5b876fa6da5be5_47455574 in /home/wwwroot/default/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php:128
#25 Smarty_Template_Resource_Base:getRenderedTemplateCode in /home/wwwroot/default/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:172
#24 Smarty_Template_Compiled:render in /home/wwwroot/default/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:206
#23 Smarty_Internal_Template:render in /home/wwwroot/default/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:216
#22 Smarty_Internal_TemplateBase:_execute in /home/wwwroot/default/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:122
#21 Smarty_Internal_TemplateBase:display in /home/wwwroot/default/app/Controllers/UserController.php:1061
#20 App\Controllers\UserController:invite in /home/wwwroot/default/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#19 call_user_func in /home/wwwroot/default/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#18 Slim\Handlers\Strategies\RequestResponse:__invoke in /home/wwwroot/default/vendor/slim/slim/Slim/Route.php:366
#17 Slim\Route:__invoke in /home/wwwroot/default/app/Middleware/Auth.php:43
#16 App\Middleware\Auth:__invoke in /home/wwwroot/default/vendor/slim/slim/Slim/DeferredCallable.php:46
#15 call_user_func_array in /home/wwwroot/default/vendor/slim/slim/Slim/DeferredCallable.php:46
#14 Slim\DeferredCallable:__invoke in /home/wwwroot/default/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:73
#13 call_user_func in /home/wwwroot/default/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:73
#12 Slim\Route:Slim\{closure} in /home/wwwroot/default/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:122
#11 Slim\Route:callMiddlewareStack in /home/wwwroot/default/vendor/slim/slim/Slim/Route.php:334
#10 Slim\Route:run in /home/wwwroot/default/vendor/slim/slim/Slim/App.php:545
#9 Slim\App:__invoke in /home/wwwroot/default/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php:70
#8 Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware:__invoke in /home/wwwroot/default/vendor/slim/slim/Slim/DeferredCallable.php:46
#7 call_user_func_array in /home/wwwroot/default/vendor/slim/slim/Slim/DeferredCallable.php:46
#6 Slim\DeferredCallable:__invoke in /home/wwwroot/default/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:73
#5 call_user_func in /home/wwwroot/default/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:73
#4 Slim\App:Slim\{closure} in /home/wwwroot/default/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:122
#3 Slim\App:callMiddlewareStack in /home/wwwroot/default/vendor/slim/slim/Slim/App.php:438
#2 Slim\App:process in /home/wwwroot/default/vendor/slim/slim/Slim/App.php:370
#1 Slim\App:run in /home/wwwroot/default/config/routes.php:368
#0 require in /home/wwwroot/default/public/index.php:11

**Comment by wewall** [comment]
目测不是新安装是更新的，然后自己没更新完成
