### ISSUE TITLE
账号密码输入完毕,点击登录不能跳转,需要刷新才能进入

### ISSUE THREAD

**Issue by 1arry1awrence** [NimaQu/ss-panel-v3-mod_Uim#251]
账号密码输入完毕,点击登录不能跳转,需要刷新才能进入,麻烦看一下.自从更新了代码之后就这样,以前是好的.

**Comment by 1arry1awrence** [comment]
是js有问题吗,没弹出图片

**Comment by NimaQu** [comment]
无法复制

**Comment by 1arry1awrence** [comment]
http://www.nansanjianqu.fun
账号:123@qq.com
密码:123123123
可以登一下,帮忙看看
