### ISSUE TITLE
500error

### ISSUE THREAD

**Issue by gaoyan1234** [NimaQu/ss-panel-v3-mod_Uim#260]
按照教程安装显示500错误  开启debug模式 加粗行 显示 /app/Controllers/UserController.php 740行
syntax error, unexpected '[' 错误

                    $node_latestload[$name_cheif]=((float)(explode(" ",$nodeLoad[0]['load']))[0])*100;

**Comment by CGDF-Github** [comment]
php版本多少

**Comment by NimaQu** [comment]
我怎么记得这个是远古版本才有的问题

**Comment by CGDF-Github** [comment]
php5.x会导致这个问题

**Comment by wewall** [comment]
php8.1 会这样？

**Comment by akqzx** [comment]
php7.1完美可用
