### ISSUE TITLE
订阅链接的问题

### ISSUE THREAD

**Issue by laurieryayoi** [NimaQu/ss-panel-v3-mod_Uim#267]
commit 8d4b6ba7255de50636479f80c60f39cb3363dede

同时订阅普通端口A和单端口B，A在客户端上面，B在A下面
重置订阅链接后的第一次更新，A和B的所有节点都可以更新到
再次更新订阅，A的所有节点会被B覆盖，即所有节点都变成了单端口

![img](https://puu.sh/Bsd9j/8f5a08e3fa.jpg)
这是重置端口后第一次更新订阅
![img](https://puu.sh/Bsdar/79301a0026.jpg)
这是再次更新订阅

5.15客户端订阅的过期时间和剩余流量会冲突，两者不能并存（是客户端的问题）

**Comment by CGDF-Github** [comment]
请尝试一下4.9版的客户端是否会出现此问题
https://github.com/shadowsocksrr/shadowsocksr-csharp/releases

**Comment by laurieryayoi** [comment]
会出现，上面的图是4.8客户端的
![img](https://puu.sh/Bseos/05908503b2.jpg)
这是4.9的，可以看到只有剩余流量，过期时间没了

**Comment by NimaQu** [comment]
已修复，请更新测试
