### ISSUE TITLE
注册问题

### ISSUE THREAD

**Issue by laurieryayoi** [NimaQu/ss-panel-v3-mod_Uim#268]
commit 28ba2b4d1441435d2a4123945fcd778e6ba8fad6

用邀请链接注册，点同意后没有反应，用户数量没有增加，但是邀请链接使用数会-1
已经更新过.config.php

~~另外我发现演示站不能删除用户~~

**Comment by CGDF-Github** [comment]
请检查是否为dev最新版本

**Comment by laurieryayoi** [comment]
最新版dev已经解决
