### ISSUE TITLE
关于商品重置流量的问题

### ISSUE THREAD

**Issue by Adosh** [NimaQu/ss-panel-v3-mod_Uim#274]
在编辑商品页面“续费时自动重置用户流量为上面这个流量值”为关闭状态，设定为添加10G流量后购买，流量会被重置为10G，并不会在原有流量基础上增加10G。

以上问题已在demo站复现。

**Comment by NimaQu** [comment]
@Adosh 好好看一遍你的 config

**Comment by Adosh** [comment]
@NimaQu 是我的问题，不好意思。
