### ISSUE TITLE
邀请链接似乎存在问题 +_+

### ISSUE THREAD

**Issue by ViktorFuang** [NimaQu/ss-panel-v3-mod_Uim#275]
目前邀请链接似乎存在问题，邀请链接复制到浏览器打开页面，会直接跳转到注册页面，后面的参数?code=没有了，无法正确完成邀请及返利动作。
本来以为是环境问题，后在官方demo上测试，情况依旧，似乎都有问题。

**Comment by NimaQu** [comment]
不强制邀请码的情况下是用 cookies 的，所以直接不用填写，你可以测试下

**Comment by ViktorFuang** [comment]
也就是说，是cookies的问题？ 如果其他电脑上曾经存在cookies，就无法完成邀请。

**Comment by NimaQu** [comment]
@ViktorFuang 不清楚，我这里测试是可以正常邀请返利的
