### ISSUE TITLE
请求增加支持xpay的支持

### ISSUE THREAD

**Issue by coldeve** [NimaQu/ss-panel-v3-mod_Uim#276]
源代码在这里，不需要第三方支持，看起来不错，谢谢了

**Comment by CGDF-Github** [comment]
没什么屌用，这个xpay的每笔支付都是需要人工审核的，并不会像码支付一样自动读取收款记录然后自动充值，而是需要站长自己手动打开支付宝app，校对有没有收到钱，然后手动打开网站给用户放款。【so，与其用这个xpay，为什么不用sspanel内置的充值码功能？】

**Comment by coldeve** [comment]
> 没什么屌用，这个xpay的每笔支付都是需要人工审核的，并不会像码支付一样自动读取收款记录然后自动充值，而是需要站长自己手动打开支付宝应用程序，校对有没有收到钱，然后手动打开网站给用户放款。【所以，与其用这个xpay，为什么不用sspanel内置的充值码功能？】

谢谢 了解了
