### ISSUE TITLE
续费同等级套餐会重置等级到期时间

### ISSUE THREAD

**Issue by lw960105** [NimaQu/ss-panel-v3-mod_Uim#287]
一级升二级套餐重置等级到期时间，但是最近版本一级续费一级套餐也重置等级到期时间了

**Comment by CGDF-Github** [comment]
https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues/201

**Comment by lw960105** [comment]
@CGDF-Github   懂了   但是续费同等级商品时重置等级时间会不会有点不妥，假设我是新用户，我买了一个月套餐，还有10天到期，我还想在买一个月，等级时间按理说也要叠加，直接重置是不是有点不妥？因为季付年付用户比例还是比较少的，或者续费同等级-等级到期时间叠加-不是同等级重置。

**Comment by CGDF-Github** [comment]
@lw960105 那为什么不使用【自动续费】？

**Comment by lw960105** [comment]
@CGDF-Github   嗯  但是手动续费的多  开启自动续费  很多人不懂关闭  想充值多点进去 买季度套餐  结果又自动续费了上次的套餐，你说的防止用户低价格买高等级流量套餐也有道理，  或许还有其他更好思路？
