### ISSUE TITLE
底部footer与节点二维码重叠

### ISSUE THREAD

**Issue by kizimiV** [NimaQu/ss-panel-v3-mod_Uim#292]
最新的firefox渲染出来的网页，底部footer会与“节点列表”内的节点二维码重叠，有些时候可能无法扫描成功
![1](https://user-images.githubusercontent.com/38457218/45929714-00b04200-bf45-11e8-800e-1de269498fc6.png)

**Comment by wewall** [comment]
这个问题, 很玄学, 出现已经很久了, 不是100% 重现, 也没有重现明确步骤.

**Comment by wewall** [comment]
@NimaQu  我们听听 Qu 先生怎么说

**Comment by NimaQu** [comment]
@wewall footer 的 css 有问题....以前好好的，不知道从哪个 commit开始就这样了，设置成 fixed 就这样的，设置成 absolute 的时候user飘中间login 正常

**Comment by CGDF-Github** [comment]
@NimaQu 这个应该是我改的，有空我修

**Comment by CGDF-Github** [comment]
https://github.com/NimaQu/ss-panel-v3-mod_Uim/commit/347df01125b28d03324e9804cca7ecc6e807a925

FIXED

可能需要ctrl+f5才能显示新的css效果，如果配置了CDN，请先清空CDN缓存
