### ISSUE TITLE
后台添加商品那里: 每多少天内，每多少天，重置流量为多少G。不能重制流量！

### ISSUE THREAD

**Issue by Hsuye** [NimaQu/ss-panel-v3-mod_Uim#293]
例如我添加一个商品 流量30G  等级有效期30天 每30天内 每1天 重制流量为30G
今天用了10G 明天流量也不重制

**Comment by Chennhaoo** [comment]
参照wiki设置好定时任务，然后php解禁system函数，如果你是今天下午买的套餐，那么今天晚上12点是不会重置的，明天晚上12点才会。
回答完毕，如果还是不行，请付费找大佬。
