### ISSUE TITLE
流量使用情况的图流量全部计入今日，没有过去已用

### ISSUE THREAD

**Issue by liwenjie119** [NimaQu/ss-panel-v3-mod_Uim#296]
![default](https://user-images.githubusercontent.com/25956275/46007183-f7ada500-c0eb-11e8-91ab-f7ca43af02e7.png)

如图所示，流量统计有问题。。。刚装好的时候是正常的，用着用着就出问题了，更新了一下还是这样

**Comment by Chennhaoo** [comment]
这个流量一般是晚上12点更新

**Comment by CGDF-Github** [comment]
请确认今日是否重置了流量

**Comment by liwenjie119** [comment]
没重置过

> 请确认今日是否重置了流量

没有重置过流量，只是有时候会重启ssr后端

**Comment by CGDF-Github** [comment]
daliyjob还能正常执行吗？

**Comment by 1192636025** [comment]
能具体解释一下吗

**Comment by CGDF-Github** [comment]
手动执行
```
0 0 * * * php -n /网站目录/xcat dailyjob
```
可以正常执行吗

**Comment by 1192636025** [comment]
不能执行command

**Comment by CGDF-Github** [comment]
那你tm倒是把output贴上来啊

**Comment by TBQin** [comment]
话说你们都没有发现CDN挂了吗？

**Comment by NimaQu** [comment]
@TBQin 有吗？

**Comment by TBQin** [comment]
![11](https://user-images.githubusercontent.com/25794322/46072150-360e9700-c1b4-11e8-9fd6-c41688b34bb9.png)
首页登录按钮没反应 用户列表 中转规则都不能编辑

**Comment by NimaQu** [comment]
是最新版 dev?

**Comment by liwenjie119** [comment]
最新版的dev。手动执行 php -n xcat dailyjob
[root@InfantileZesty-VM guoqiangti.ml]# php -n xcat dailyjob
rm: cannot remove ‘/www/wwwroot/guoqiangti.ml/storage/*.png’: No such file or directory

Fatal error: Uncaught TelegramBot\Api\HttpException: Bad Request: chat not found in /www/wwwroot/guoqiangti.ml/vendor/telegram-bot/api/src/BotApi.php:281
Stack trace:
#0 /www/wwwroot/guoqiangti.ml/vendor/telegram-bot/api/src/BotApi.php(258): TelegramBot\Api\BotApi::curlValidate(Resource id #99, '{"ok":false,"er...')
#1 /www/wwwroot/guoqiangti.ml/vendor/telegram-bot/api/src/BotApi.php(227): TelegramBot\Api\BotApi->executeCurl(Array)
#2 /www/wwwroot/guoqiangti.ml/vendor/telegram-bot/api/src/BotApi.php(337): TelegramBot\Api\BotApi->call('sendMessage', Array)
#3 /www/wwwroot/guoqiangti.ml/app/Utils/Telegram.php(18): TelegramBot\Api\BotApi->sendMessage('1001313577132', '\xE5\xA7\x90\xE5\xA7\x90\xE5\xA7\x90\xE5\xA7\x90\xEF\xBC\x8C...')
#4 /www/wwwroot/guoqiangti.ml/app/Command/Job.php(142): App\Utils\Telegram::Send('\xE5\xA7\x90\xE5\xA7\x90\xE5\xA7\x90\xE5\xA7\x90\xEF\xBC\x8C...')
#5 /www/wwwroot/guoqiangti.ml/app/Command/XCat.php(76): App\Command\Job::DailyJob()
#6 /www/wwwroot/guoqiangti.ml/xcat(11): App\Command\XCat->boot()
 in /www/wwwroot/guoqiangti.ml/vendor/telegram-bot/api/src/BotApi.php on line 281

**Comment by liwenjie119** [comment]
网站启用https，后端ssr设置"redirect": ["*:443#127.0.0.1:8888"]，git pull 至最新没问题，执行php xcat update后网站无法打开，必须从新导入备份的.config才行，不知道哪的问题，不知道与上边的问题是否有关

**Comment by NimaQu** [comment]
我这里毛问题没有啊

**Comment by CGDF-Github** [comment]
@TBQin 这和cdn有个jb关系，你还不如打开DEBUG模式看看报什么error，居然闲的蛋疼看这里的输出

**Comment by TBQin** [comment]
![1](https://user-images.githubusercontent.com/25794322/46074635-bafcaf00-c1ba-11e8-9e71-345b90db8ccf.png)
不是CDN的问题吗，那我重置下 重新试试

**Comment by TBQin** [comment]
@CGDF-Github 我是git pull 点登陆没反应才看下的，试了下备用站升级也这样，目前只能降级了

**Comment by CGDF-Github** [comment]
https://cdn.jsdelivr.net/npm/jquery@2.2.1

你那边的网络打不开这个？

**Comment by TBQin** [comment]
@CGDF-Github额 晚上发现可以了 谢谢大佬

**Comment by TBQin** [comment]
![11](https://user-images.githubusercontent.com/25794322/46076759-1893fa00-c1c1-11e8-98d5-37f745282cc7.png)

**Comment by CGDF-Github** [comment]
CDN相关事宜请咨询@SukkaW
或自行对照https://github.com/NimaQu/ss-panel-v3-mod_Uim/commits?author=SukkaW进行更改

**Comment by SukkaW** [comment]
@TBQin @CGDF-Github DNS 问题请自行更换本地递归 DNS 解决，jsDelivr 上游权威 DNS 在停用 cedexis 以后并无任何新的 issue，参见 https://github.com/jsdelivr/jsdelivr/issues/18094
而且，sspanel 登录页面没有使用 HTML5 表单、高度依赖 jquery，如果 CDN 有问题是连登录都无法完成。如果能登录而其他功能异常，是其它问题导致的。

**Comment by SukkaW** [comment]
@CGDF-Github 如果暴露一个 config，我可以实现按配置选择加载位置。

**Comment by CGDF-Github** [comment]
@SukkaW 

https://github.com/NimaQu/ss-panel-v3-mod_Uim/compare/788bad0251bc...34b135aca8aa

$System_Config['load_mode_js']='local';	//JS加载方式，local为从panel本地加载，jsdelivr为从CDN加载

**Comment by TBQin** [comment]
@SukkaW大佬，最新版点登陆没有反应的，我只能降级到旧的版本。我挂了Cloudflare的，现在是改下前端DNS？还是等您pr好根据配置选择加载位置
