### ISSUE TITLE
运行同步用户数据：php xcat syncusers 失败

### ISSUE THREAD

**Issue by coldeve** [NimaQu/ss-panel-v3-mod_Uim#298]
阿里云 香港vps 1核1g 全新安装
安装前端时，运行php xcat syncusers显示
![default](https://user-images.githubusercontent.com/24355466/46048341-65dd8080-c15b-11e8-8b26-f2c01e60ccff.PNG)

貌似是php错误，可是我将php所有模块都安装了还是有相同错误

**Comment by coldeve** [comment]
为什么关闭？
请问哪里问的不对

**Comment by NimaQu** [comment]
@coldeve 自己安装问题，，，

**Comment by coldeve** [comment]
> @coldeve自己安装问题,,,

抱歉，我是先按照wiki上，接着是91vps，现在是https://www.ryoeiken.com/archives/61/的安装步骤，一直安装出这个报错。
重装了一个多星期了，实在是没办法才问的。
请问具体是哪一环节出错了？

**Comment by coldeve** [comment]
了解了，安全组设置问题

**Comment by coldeve** [comment]
额 喔安全组设置全通 iptables全通，完全按照https://www.ryoeiken.com/archives/61/方法，参考wiki的方法，请问能不能给我个错误范围，我实在是不清楚哪个地方出问题了。
弄了快一个星期了

**Comment by coldeve** [comment]
知道哪里错了。
阿里云不支持应该也不允许用mailgun协议发送邮件
当我把$System_Config['mailDriver'] = 'smtp';里面设置为smtp，保存后，立马好了
不是安装也不是配置环境问题
就是邮箱需要设置smtp

**Comment by coldeve** [comment]
已更新wiki

**Comment by CGDF-Github** [comment]
@coldeve 你瞎JB改什么？谁告诉你要填邮件设置了？

**Comment by coldeve** [comment]
抱歉 我填了后发现不对选择恢复历史记录了，没想到还有啊，实在是抱歉
