### ISSUE TITLE
请求支付宝二维码问题

### ISSUE THREAD

**Issue by blakelu** [NimaQu/ss-panel-v3-mod_Uim#300]
请求成功后,此处代码执行问题
$("#qrcode").html(data.qrcode);
$("#info").html("您的订单金额为："+data.amount+"元。");

由于dom节点有2个qrcode 与info的id
建议使用class作为选择器

**Comment by wewall** [comment]
有这个想法, 可能请您自己修改然后创建一个新的 Pull Request 呢.
