### ISSUE TITLE
请求支付宝当面付提示全局函数找不到

### ISSUE THREAD

**Issue by blakelu** [NimaQu/ss-panel-v3-mod_Uim#301]
![_7aa9853d-6050-4c17-83de-e1b5bad64364](https://user-images.githubusercontent.com/13463232/46079125-cbb42180-c1c8-11e8-84f2-d0de5a389813.png)
本人解决方案是在项目根目录下的composer.json动态加载全局函数，添加完这2行代码后，用终端进入到项目目录下执行如下命令即可
```
composer dump-autoload
```

**Comment by NimaQu** [comment]
![1.png](https://i.loli.net/2018/09/26/5bab79abdfd2a.png)

**Comment by blakelu** [comment]
这个我试过了，不生效。 我现在还在找这个的原因
