### ISSUE TITLE
希望把商品续费逻辑修改下

### ISSUE THREAD

**Issue by lw960105** [NimaQu/ss-panel-v3-mod_Uim#303]
用户续费重置时间有点不妥  其实以前那个逻辑挺好的  只要设置好套餐就行。
 续费同等级套餐时:时间不重置
 续费不同等级套餐时:重置等级到期时间

**Comment by CGDF-Github** [comment]
所以你他妈倒是说一下哪里不妥？
之前的功能好在哪里？
现在的功能差在哪里？
什么论据都没有，全靠空口逼逼？
还尼玛开两个issue来逼逼，一个issue已经不够你尽情驰骋了吗？你他妈先动动脑子行不行？

你之前提的弱智要求我都给你解决方案了，
那你倒是告诉我一下：旧方案下如果想设置【购买就充值等级到期时间】要怎么弄？

【套餐叠加】本来就不是SSPANEL建议的套餐方式，不然购买套餐的时候为什么不问你【购买数量】？

你当SSPANEL是为你一个人设计的吗？
