### ISSUE TITLE
checkjob不工作

### ISSUE THREAD

**Issue by TBQin** [NimaQu/ss-panel-v3-mod_Uim#310]
/home/wwwroot/www.$ php xcat checkjob
PHP Warning:  unlink(/home/wwwroot/www/storage/traffic_notified/253.userid): No such file or directory in /home/wwwroot/wwwf/app/Command/Job.php on line 353
PHP Warning:  unlink(/home/wwwroot/www/storage/traffic_notified/375.userid): No such file or directory in /home/wwwroot/www/app/Command/Job.php on line 353
PHP Notice:  Undefined index: load_mode_js in /home/wwwroot/www/app/Services/Config.php on line 10
PHP Warning:  fopen(/home/wwwroot/www/storage/traffic_notified/405.userid): failed to open stream: No such file or directory in /home/wwwroot/www./app/Command/Job.php on line 344
Unable to open file!

**Comment by TBQin** [comment]
好像是检测用户剩下流量的，我删除这个代码就提示检测GFW的出错

**Comment by TBQin** [comment]
现在是节点掉线没提醒，用户到期不删除

**Comment by CGDF-Github** [comment]
语无伦次地说的啥玩意儿，你xcat update过了？

**Comment by TBQin** [comment]
@CGDF-Github = =大佬别在意，php xcat update吗 之前升级了，我运行php xcat checkjob提示上面的错误 想问下怎么解决

**Comment by CGDF-Github** [comment]
出现这个错误说明你xcat update压根没执行成功

**Comment by TBQin** [comment]
@CGDF-Github 我运行php xcat update 提示迁移成功的= =那里还要操作下吗 ，小白见谅见谅

**Comment by CGDF-Github** [comment]
把xcat update所有输出都贴上来

**Comment by TBQin** [comment]
![qq 20180928211801](https://user-images.githubusercontent.com/25794322/46210688-01414200-c364-11e8-9dd4-ab78851fa389.png)
我刚刚升级了 现在提示

**Comment by CGDF-Github** [comment]
然后重新运行checkjob再贴出运行结果
