### ISSUE TITLE
notify_limit_mode邮件风暴

### ISSUE THREAD

**Issue by laurieryayoi** [NimaQu/ss-panel-v3-mod_Uim#318]
commit 8cace47ba03da3747509011e97057ddb5376b4a8
百分比模式
只判断了是不是要发
没判断已经发了没
于是无限发邮件

**Comment by NimaQu** [comment]
是最新版本？

**Comment by laurieryayoi** [comment]
> 是最新版本？

对

**Comment by CGDF-Github** [comment]
https://github.com/NimaQu/ss-panel-v3-mod_Uim/compare/187ac7b81fc4...91c95fb05e9a
fixed

**Comment by laurieryayoi** [comment]
测试已经修复（
