### ISSUE TITLE
chenPay 钱收到了账户钱没到账

### ISSUE THREAD

**Issue by hai2012** [NimaQu/ss-panel-v3-mod_Uim#319]
1.此项目为前端，不解决任何后端对接相关问题

2.提问前请先阅读 wiki,否则将会 close 并 block

3.有问题先去 https://demo.nimaqu.com 测试，再写明如何复现这个问题，否则按上条处理

4.issues 是反馈 bug / 提供建议的，不是问问题的，不会装面板的自己去交流群花钱请人装

5.发 issue 前，请在面板路径下运行`git show HEAD`，然后在 issue 中贴上输出内容，以便定位问题

6.发 issue 之前麻烦把这些东西删了再发

**Comment by ChenSee** [comment]
https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E6%94%AF%E4%BB%98%E7%B3%BB%E7%BB%9F%E5%AF%B9%E6%8E%A5%E6%95%99%E7%A8%8B 看这个
