### ISSUE TITLE
单端口订阅问题

### ISSUE THREAD

**Issue by pyrj56** [NimaQu/ss-panel-v3-mod_Uim#322]
在同时添加单端口订阅和普通端口订阅时，第一次更新订阅可以正常显示所有节点。第二次更新订阅后普通端口节点全部消失，只剩下单端口节点。
  已通过git pull更新到最新版本，客户端使用ShadowsocksR-win-4.9.0。

**Comment by pyrj56** [comment]
大佬你好，我这普通端口和单端口订阅生成的是相同的分组，安装时使用的是wiki中宝塔一键前端安装。

**Comment by laurieryayoi** [comment]
master有这个问题，dev已经修复

**Comment by pyrj56** [comment]
谢谢大佬
