### ISSUE TITLE
f2f充值问题，支付宝已到账但网站没到账

### ISSUE THREAD

**Issue by lhongtao666** [NimaQu/ss-panel-v3-mod_Uim#328]
issue. f2f充值问题，支付宝已到账但网站没到账。
已经到https://demo.nimaqu.com测试过，
https://demo.nimaqu.com也存在这个情况。
前面我试过按原版系统手动重装alipay，也不行。
刚开始我用的是dev分支，换成master也不行，https://demo.nimaqu.com也不行。

HEAD如下
-----------------------------------------------------------------------------------------------
commit 73a7571e1cc11ce80ed6be70dd9a1d2abad84b5b
Author: NimaQu <i@nimaqu.com>
Date:   Sat Sep 8 21:12:31 2018 +0800

    修改文字说明

diff --git a/resources/views/material/admin/find.tpl b/resources/views/material/
index 26cfcd1..0d6508c 100644
--- a/resources/views/material/admin/find.tpl
+++ b/resources/views/material/admin/find.tpl
@@ -69,19 +69,19 @@
                                                <div class="card">
                                                 <div class="card-main">
                                                         <div class="card-inner"
-                                                       <p>用户名：{$userf->user
+
                                                         <p>邮箱：{$userf->email
                                                         <p>端口：{$userf->port}
 <hr>
                                                         <p>等级：{$userf->class
-                                                        <p>等级0过期时间：{$use
-                                                     <p>等级1过期时间：{$userf-
+                                                        <p>账户过期时间：{$user
:...skipping...
commit 73a7571e1cc11ce80ed6be70dd9a1d2abad84b5b
Author: NimaQu <i@nimaqu.com>
Date:   Sat Sep 8 21:12:31 2018 +0800

    修改文字说明

diff --git a/resources/views/material/admin/find.tpl b/resources/views/material/admin/find.tpl
index 26cfcd1..0d6508c 100644
--- a/resources/views/material/admin/find.tpl
+++ b/resources/views/material/admin/find.tpl
@@ -69,19 +69,19 @@
                                                <div class="card">
                                                 <div class="card-main">
                                                         <div class="card-inner">
-                                                       <p>用户名：{$userf->user_name}</p>
+                                                                                                               <p>用户名：{$userf->user_name}</p>
                                                         <p>邮箱：{$userf->email}</p>
                                                         <p>端口：{$userf->port}</p>
 <hr>
                                                         <p>等级：{$userf->class}</p>
-                                                        <p>等级0过期时间：{$userf->expire_in}</p>
-                                                     <p>等级1过期时间：{$userf->class_expire}</p>
+                                                        <p>账户过期时间：{$userf->expire_in}</p>
+                                                                                                               <p>等级过期时间：{$userf->class_expire}</p>
 <hr>
                                                         <p>总流量：{$userf->enableTraffic()}</p>
                                                         <p>已用流量：{$userf->LastusedTraffic()}</p>
                                                         <p>金钱：{$userf->money}</p>
 <hr>
-                                                       <a class="btn btn-brand btn-flat waves-attach" href="/admin/user/{$userf->id}/edit" target="_blank" ><font style="color:green"><span class="icon">check</span>&nbsp;编辑</font></a>
+                                                                                                               <a class="btn btn-brand btn-flat waves-attach" href="/admin/user/{$userf->id}/edit" target="_blank" ><font style="color:green
                                                         &nbsp;&nbsp;<a class="btn btn-brand btn-flat waves-attach" id="delete"  ><font style="color:red"><span class="icon">close</span>&nbsp;删除</font></a>

**Comment by wewall** [comment]
@lhongtao666 韩红看了都想打人

**Comment by lhongtao666** [comment]
在数据库中查看paylist表 充值状态是0

**Comment by NimaQu** [comment]
demo.nimaqu.com 刚刚是 dev ，现在切到 master 了，master 是没问题的

**Comment by tonyzzzzzz** [comment]
@lhongtao666 请附一下 PHP Log 关于 回调有关的报错。关键字 notify

**Comment by lhongtao666** [comment]
2018/10/09 22:49:25 [error] 11608#0: *123687 FastCGI sent in stderr: "PHP message: Slim Application Error:
Type: Error
Message: Call to protected method App\Services\Gateway\AopF2F::notify() from context 'App\Services\Payment'
File: /www/wwwroot/fllsis.bingcloud.net/app/Services/Payment.php
Line: 41
Trace: #0 [internal function]: App\Services\Payment::notify(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#1 /www/wwwroot/fllsis.bingcloud.net/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 /www/wwwroot/fllsis.bingcloud.net/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /www/wwwroot/fllsis.bingcloud.net/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 /www/wwwroot/fllsis.bingcloud.net/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim" while reading response header from upstream, client: 110.75.248.179, server: fllsis.bingcloud.net, request: "POST /pay_callback HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi-71.sock:", host: "fllsis.com"

**Comment by lhongtao666** [comment]
2018/10/09 22:59:24 [error] 11609#0: *124566 FastCGI sent in stderr: "PHP message: Slim Application Error:
Type: Error
Message: Call to protected method App\Services\Gateway\AopF2F::notify() from context 'App\Services\Payment'
File: /www/wwwroot/fllsis.bingcloud.net/app/Services/Payment.php
Line: 41
Trace: #0 [internal function]: App\Services\Payment::notify(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#1 /www/wwwroot/fllsis.bingcloud.net/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 /www/wwwroot/fllsis.bingcloud.net/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /www/wwwroot/fllsis.bingcloud.net/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 /www/wwwroot/fllsis.bingcloud.net/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim" while reading response header from upstream, client: 110.75.248.209, server: fllsis.bingcloud.net, request: "POST /pay_callback HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi-71.sock:", host: "fllsis.com"
2018/10/09 23:02:19 [error] 11607#0: *124900 FastCGI sent in stderr: "PHP message: Slim Application Error:
Type: Error
Message: Call to protected method App\Services\Gateway\AopF2F::notify() from context 'App\Services\Payment'
File: /www/wwwroot/fllsis.bingcloud.net/app/Services/Payment.php
Line: 41
Trace: #0 [internal function]: App\Services\Payment::notify(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#1 /www/wwwroot/fllsis.bingcloud.net/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 /www/wwwroot/fllsis.bingcloud.net/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /www/wwwroot/fllsis.bingcloud.net/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 /www/wwwroot/fllsis.bingcloud.net/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim" while reading response header from upstream, client: 110.75.248.10, server: fllsis.bingcloud.net, request: "POST /payment/notify HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi-71.sock:", host: "fllsis.com"

这两个重复出现，我换成master并把$System_Config['baseUrl']的值改为和访问网站一致后问题也解决了。如果不一样也不行
