### ISSUE TITLE
用户中心VIP节点不显示

### ISSUE THREAD

**Issue by srunin** [NimaQu/ss-panel-v3-mod_Uim#33]
在后台添加节点等级非0的时候不论用户等级多少，VIP节点都不显示，只显示免费节点，在SSR客户端添加订阅可以正常订阅

**Comment by mxihan** [comment]
试着把node.tpl中第170行的 ` {if $node_isv6[$prefix] == 0 && $node_class[$prefix]==1} `  里的==1改成!=0

**Comment by mxihan** [comment]
该问题已在新版本中修复
