### ISSUE TITLE
简单问题 滚动栏挡住了设置键

### ISSUE THREAD

**Issue by lhongtao666** [NimaQu/ss-panel-v3-mod_Uim#331]
![default](https://user-images.githubusercontent.com/29915310/46778639-39268d00-cd47-11e8-8fb1-8f7bc6ec506f.png)

简单问题 滚动栏挡住了设置键

**Comment by wewall** [comment]
@lhongtao666 咦，有点东西

**Comment by tonyzzzzzz** [comment]
@lhongtao666 贵站 https://fllsis.com/ 请尽快恢复被删除的 STAFF 入口。

**Comment by CGDF-Github** [comment]
dev分支已优化了这个问题
