### ISSUE TITLE
码支付对账用户列随机值

### ISSUE THREAD

**Issue by michellrobert** [NimaQu/ss-panel-v3-mod_Uim#333]
从master换到dev后，发现码支付对账时用户栏从原来的USERID换成了随机值，码支付日常掉单...现在只能通过时间对应判断了
![qq 20181020193145](https://user-images.githubusercontent.com/39368963/47255143-ebc0c300-d49e-11e8-8769-e891671780a9.png)

**Comment by NimaQu** [comment]
改回来了
