### ISSUE TITLE
添加了自动备份，并设置了1440分钟。备份一次。   但是不生效

### ISSUE THREAD

**Issue by zs910208565** [NimaQu/ss-panel-v3-mod_Uim#336]
![screenshot_2018-10-25-08-51-58-826_com tencent mm](https://user-images.githubusercontent.com/34202810/47469397-49546700-d833-11e8-9765-da9807b36700.png)
![img_20181025_085035](https://user-images.githubusercontent.com/34202810/47469398-49ecfd80-d833-11e8-9154-baba5d5aa9e7.png)

请问下，备份那原始代码在哪个位置！

**Comment by anserme** [comment]
crontab直接设置天数试试看吧

**Comment by CGDF-Github** [comment]
crontab第一项上限为60

例1：每20分钟备份1次（若间隔大于60分钟，看例2）：
*/20 * * * * php -n /网站目录/xcat backup

例2：每20小时备份1次（若间隔大于24小时，自行Google）：
0 */20 * * * php /path/to/your/cron.php
