### ISSUE TITLE
黛米付无法支付

### ISSUE THREAD

**Issue by mayingjiejiejie** [NimaQu/ss-panel-v3-mod_Uim#338]
![default](https://user-images.githubusercontent.com/38562796/47590851-357a4380-d9a0-11e8-8aa2-2ca77a262450.png)
重新拉取了一次代码发现还是这个样子

**Comment by NimaQu** [comment]
本来就没修，急什么

**Comment by mayingjiejiejie** [comment]
额额

**Comment by NimaQu** [comment]
现在看看

**Comment by mayingjiejiejie** [comment]
大佬威武~

**Comment by opoet** [comment]
感觉这个有必要修一下emmm。。

**Comment by NimaQu** [comment]
@opoet 修个jb 早就修了

**Comment by opoet** [comment]
好吧怪我没有xat update 不好意思
