### ISSUE TITLE
是否可以仿一个不需要切换苹果id就能安装客户端的骚操作

### ISSUE THREAD

**Issue by Hoverclouds** [NimaQu/ss-panel-v3-mod_Uim#339]
隔壁胖虎出了一个骚操作，可以免切换账号就能安装ipa，我们是不是也可以做一个
来源如下：
https://github.com/ssrpanel/SSRPanel/wiki/iOS免切换账号在线安装Shadowrocket

**Comment by wewall** [comment]
@Hoverclouds  是啊， 可以做一个， 最好自动唤起 Safari， 加油， 写好以后 prpr

**Comment by yangdec** [comment]
这个很简单，教程：https://www.jianshu.com/p/e43f75b4bd4a
ipa文件用老版的itunes可以直接下。

**Comment by galaxychuck** [comment]
@Hoverclouds 經過測試，每個機場主需要自己去拉取自己海外AppStore的小飛機IPA。該issues #339 只適用於有一定動手能力的機場主！
After testing, each webmaster needs to pull the IPA of his overseas AppStore. The issues #339 is only available for webmasters with a certain ability!

**Comment by NimaQu** [comment]
经讨论，不添加此功能，因为 Shadowrocket 非免费软件，此行为会损害软件开发者的利益
