### ISSUE TITLE
充值码无法充值

### ISSUE THREAD

**Issue by wzw1997007** [NimaQu/ss-panel-v3-mod_Uim#341]
如题，自己后台生成的充值码无法充值，点充值按钮没反应

git show HEAD 输出：
`commit ab53cd15bb204dc03330ca16d62295fda8d21de9`
`Merge: 12cfc06 9d80f64`
`Author: CGDF <17256673+CGDF-Github@users.noreply.github.com>`
`Date:   Tue Oct 30 23:16:46 2018 +0800`
`    Merge branch 'dev' of https://github.com/NimaQu/ss-panel-v3-mod_Uim into dev`

**Comment by wewall** [comment]
@wzw1997007 我觉得您没说问题所在， 您应该 F12

**Comment by wzw1997007** [comment]
查了一下问题所在，是最新的dev分支中resources/views/material/user/code.tpl的JS没有了，把之前的JS加上即可解决

**Comment by wewall** [comment]
@wzw1997007 感谢， 目测这是 @tonyzzzzzz 写的bug近期会修复，为了稳定，建议您使用master分支

**Comment by wewall** [comment]
e29f13eddcd4d4f178885232ecfbb61429108487
