### ISSUE TITLE
码支付同一账号连续付款问题

### ISSUE THREAD

**Issue by laurieryayoi** [NimaQu/ss-panel-v3-mod_Uim#342]
c3137325dccdc799643f0e41929d26cb089bf052

同一个人连续充值，只有第一单能入账

![img](https://puu.sh/BTMmt/fecf46c480.png)

![img](https://puu.sh/BTMnf/e98cd988f9.png)

![img](https://puu.sh/BTMmT/212005cced.png)

![img](https://puu.sh/BTMns/f41fc7a801.png)

**Comment by tonyzzzzzz** [comment]
@laurieryayoi 正在修复
