### ISSUE TITLE
V2节点展示，有重复数据

### ISSUE THREAD

**Issue by rico93** [NimaQu/ss-panel-v3-mod_Uim#343]
/resources/views/material/user/node.tpl的 103和111行获取了同样的数据 都是服务器地址

**Comment by ssrsky** [comment]
原来如此，谁写的BUG，我搞了一天才搞明白

**Comment by wewall** [comment]
不是BUG

**Comment by rico93** [comment]
一个是地址，一个是协议参数展示。 获取内容都是地址的信息哎
