### ISSUE TITLE
当面付问题，很急不知道哪里错了。大神帮忙下

### ISSUE THREAD

**Issue by mimi8280** [NimaQu/ss-panel-v3-mod_Uim#347]
#按照老大设置
https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E6%94%AF%E4%BB%98%E7%B3%BB%E7%BB%9F%E5%AF%B9%E6%8E%A5%E6%95%99%E7%A8%8B
公钥也上传了就不知道哪里错了 老是不行
![1](https://user-images.githubusercontent.com/44249005/47906709-cb443000-dec4-11e8-9972-4169968a60b2.jpg)
![2](https://user-images.githubusercontent.com/44249005/47906723-d39c6b00-dec4-11e8-870e-e83913513b7d.png)
![3](https://user-images.githubusercontent.com/44249005/47906727-d4350180-dec4-11e8-91b7-23d8fb739752.png)
![4](https://user-images.githubusercontent.com/44249005/47906728-d4cd9800-dec4-11e8-8b31-d239a2699a02.png)
![5](https://user-images.githubusercontent.com/44249005/47906729-d4cd9800-dec4-11e8-90cd-66c88f4974fa.png)
![6](https://user-images.githubusercontent.com/44249005/47906730-d5662e80-dec4-11e8-8f7e-f31549228e02.png)

设置好了一直到付款报错信息 扫描付款也不能入账到网站余额里。不知道哪里错了。大神帮忙下

**Comment by xcxnig** [comment]
@mimi8280 请进群说
