### ISSUE TITLE
chenPay二维码接口修改建议

### ISSUE THREAD

**Issue by xferget** [NimaQu/ss-panel-v3-mod_Uim#350]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题
项目演示站没在用chenPay

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

**申请添加新的特性或功能或者好的想法**
chenPay二维码采用了腾讯的http二维码接口，建议使用QRCode()生成

**Comment by xferget** [comment]
哦那就不用另外的接口了w

**Comment by xferget** [comment]
戳一下 @ChenSee

**Comment by wewall** [comment]
js 文件 最新 `dev` 分支应该存在，引用方法请查看现有方案或文档，不过本地可行性确实大于 API 考虑替换

**Comment by ChenSee** [comment]
嗯 有空改一下，在外考车。。

**Comment by ChenSee** [comment]
https://github.com/NimaQu/ss-panel-v3-mod_Uim/commit/c41b0ce3e86cf4925f5decd15a3287cd037164c9 @xferget

**Comment by xferget** [comment]
cdn.rawgit.com似乎在一些国内网络环境下无法加载
造成https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js加载失败
考虑存入本地？

**Comment by wewall** [comment]
@xferget git pull
