### ISSUE TITLE
google material design 图标可被选中为文字

### ISSUE THREAD

**Issue by xferget** [NimaQu/ss-panel-v3-mod_Uim#351]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

其实就是因为图标都是用<code>\<i class="icon icon-md"\>*\</i\></code>引用的
所以可以选择也可以复制成文字:joy:

**Comment by laurieryayoi** [comment]
~~怎么改嘛，metarial icons本来i标签里就有字~~

改了
