### ISSUE TITLE
网页老是加载很长时间

### ISSUE THREAD

**Issue by 74986748** [NimaQu/ss-panel-v3-mod_Uim#353]
网页老是显示正在连接

**Comment by taizi-tp** [comment]
@74986748 机器网络问题别怪网站文件

**Comment by 74986748** [comment]
> @ 74986748机器网络问题别怪网站文件

腾讯云服务器，用之前的版本就没这个问题，更新最新版本就有这个问题

**Comment by wewall** [comment]
@74986748  请问您的机器是 128kb/s upload 带宽吗？

**Comment by 74986748** [comment]
> @ 74986748请问 您的机器是128kb / s上传带宽吗？

是，可以正常打开网页，但打开之后还是会显示正在连接，而且在管理后台打开用户列表会提示错误，如图
![qq 20181105221429](https://user-images.githubusercontent.com/40517748/48003067-56812800-e148-11e8-87ae-c3738cf05d84.jpg)
自动重置流量日也不显示重置日了

**Comment by 74986748** [comment]
> > @ 74986748请问 您的机器是128kb / s上传带宽吗？
> 
> 是，可以正常打开网页，但打开之后还是会显示正在连接，而且在管理后台打开用户列表会提示错误，如图
> ![qq 20181105221429](https://user-images.githubusercontent.com/40517748/48003067-56812800-e148-11e8-87ae-c3738cf05d84.jpg)
> 自动重置流量日也不显示重置日了

![qq 20181105221449](https://user-images.githubusercontent.com/40517748/48003148-8e886b00-e148-11e8-96ea-c88524cbd5c1.jpg)

**Comment by laurieryayoi** [comment]
@wewall 1.机器带宽太小自然卡 2.关注tg频道，dev现在不能用于生产环境

**Comment by 74986748** [comment]
> @wewall 1.机器带宽太小自然卡 2.关注tg频道，dev现在不能用于生产环境

网站不卡，能快速打开，只是在网站内页打开后会显示正在连接，之前也有这种情况后来更新了文件就不存在这个情况了，今天又更新文件后又出现这个情况了
![qq 20181105223749](https://user-images.githubusercontent.com/40517748/48004319-d5c42b00-e14b-11e8-9d68-f2fb9fc232a0.jpg)

等不显示正在连接了那个等级和账号剩余时间才能显示出来
