### ISSUE TITLE
安装最新的master分支，充值码充值按钮失效

### ISSUE THREAD

**Issue by ayashit** [NimaQu/ss-panel-v3-mod_Uim#359]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)
--仅发现dev分支的重复问题

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题
---在demo站未发现此问题，可能是因为我是重新安装的原因

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

充值按钮没有响应
以下是chrome console 输出（我不确定是这个）

Uncaught ReferenceError: $ is not defined                code：557
at code:557

**Comment by wewall** [comment]
`F12` 截图 控制台信息

**Comment by ayashit** [comment]
刚才我将上个版本的/user/code.tpl替换了一下，问题没有了
为了复现又换回来了，谜一样的问题消失了，可以充值了，不知道怎么回事，，
刚才我试了很多次的
我已经不知道该说什么好了。。。

**Comment by NimaQu** [comment]
@ayashit cache

**Comment by wewall** [comment]
已修复 a73065cb5ea0cc27169106c6650c7334179d19c3
