### ISSUE TITLE
用户无法注册

### ISSUE THREAD

**Issue by sinydan** [NimaQu/ss-panel-v3-mod_Uim#36]
现象为点击注册后不跳转，无报错弹窗

web报错为 "GET /500 HTTP/1.1" 500 1430 "http://xxxxxxxxx/auth/register"

之前是可以正常注册的，最近更新后不行了

**Comment by NimaQu** [comment]
因为最近更新了肥羊的新用户注册奖励，需要根据 config.php.example 更新你自己的config

**Comment by sinydan** [comment]
已解决，谢谢
