### ISSUE TITLE
关于商店改动的想法

### ISSUE THREAD

**Issue by laurieryayoi** [NimaQu/ss-panel-v3-mod_Uim#363]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

之前觉得改商店难其实最大的问题在于忽视了user表里的两个值
![img](https://puu.sh/BYkDC/add2da200c.png)

现在有个想法
1.等级只用来判定是否为新购、和用户能不能看到节点信息。如果是新购那么设置上面提到的user表的两个值。
2.购买商品时，商品ID作为唯一判断，用来判断是否为续费，如果是续费那么只延长等级和账号时间其他数据都不动。
3.由2衍生的缺陷，这样需要可以设置买多个月打多少折，有多个档次就需要动数据库
4.需要一个只能等级>0才能买的加流量的包，只加流量其他数据都不动
5.至于买不同ID的套餐问题，我觉得要么就不能买只能手动改，要么就升级算差价，不能降级，或者像围墙之前搞的按百分比退款。

有两个可以删除的功能
![img](https://puu.sh/BYkMC/fd4b256038.png)
可以想得通无论什么计费方式这个功能都是没用的。
如果是按量计费就不说了，这个就是碍事的。
如果是周期重置的方式，那么这个功能还是碍事的，用脚想，买vps的时候，续费一个月难道还给你本月流量重置为没用过的状态吗，不会的，只会延后过期时间，而用了user表的那两个值以后，无论怎么续费流量重置日还是新购的那天。所以这个功能完全废。

![img](https://puu.sh/BYkQ8/5a6fd69017.png)
用了user表以后这个东西似乎可以删了，不过也有用，比如不想按月重置。
如果要保留这个功能那就要把user表里auto_reset_day的功能改成按新购流量包的里设置的周期作用

**Comment by wewall** [comment]
> 用了user表以后这个东西似乎可以删了，不过也有用，比如不想按月重置。
删不掉，之前讨论过流量计费新的方案， Qu 先生说她咕的

**Comment by dalekzhangdong** [comment]
这个是用什么工具开发得 webstrom?
