### ISSUE TITLE
单多合并时单端口直接使用普通端口配置

### ISSUE THREAD

**Issue by GregTechnology** [NimaQu/ss-panel-v3-mod_Uim#366]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

(又来丢人.jpeg)
adfaebef43358cd911077a8db857358ee8f0649e
在最新版下，围墙大佬的单端口并不能用，端口加密协议混淆导入后都是用户普通端口的设定

**Comment by wewall** [comment]
已知的bug

**Comment by wewall** [comment]
等我开机
