### ISSUE TITLE
[围墙大佬]可否咕咕咕一个[每月1号]重置用户流量的功能？

### ISSUE THREAD

**Issue by pinterester** [NimaQu/ss-panel-v3-mod_Uim#368]
**申请添加新的特性或功能或者好的想法**

**由于：原本30天重置一次流量，用户无法清晰的看到到底那一天会重置流量

所以：可否添加一个功能，设置为统一1号重置流量 （或者变为可选）**

> 这样用户就会清晰的知道[流量]重置时间，他们会考虑[购买流量] or [等待重置流量]。

感谢大佬，如何麻烦就算啦，谢谢。

**Comment by NimaQu** [comment]
不是有个注册时的流量重置日吗，你设置为1，套餐不设置重置不就好了

**Comment by Anankke** [comment]
@pinterester 自己改

**Comment by pinterester** [comment]
收到，感谢大佬解答。

**Comment by wewall** [comment]
> @pinterester 自己改

好耶，是 `Anankke`

**Comment by pinterester** [comment]
我昨天设置之后发现一些小问题，不知如何理解：

不好意思哦，又开这个，issuess。大佬见谅。

**#注册时的流量重置日以及需要重置的流量,0不重置**
> $System_Config['reg_auto_reset_day']='0';
> $System_Config['reg_auto_reset_bandwidth']='0';

1/重置日设置为`1`，（每月1号）
疑问： 买月付套餐的用户是不是会重置两次呢（购买日 and 1号）

2/ 重置流量 设置为`0` 
疑问：这个应该是0，不影响商店套餐，不知理解对不  (◑﹏◐


**#在前面重置日为`1`，重置流量为`0` 的前提下**
商店设置：`流量`为100G （前端显示：添加流量为100G）

这样应该就实现每月1号重置的目的了呢。（下跪,,,,,,,


另外：跪问大佬 商店 下架老商品，影响以前老用户的 每30天重置 效果吗？

如果可以的话这个重置日 整合到商店最好啦，嘿嘿。

萌新问题有点多，求大佬解答，心虚求教  (❤´艸｀❤     ( 瑟瑟发抖 zz.....zzz

**Comment by NimaQu** [comment]
你套餐不设置重置为什么会重置？？？既然要每月重新重置就别填套餐的重置

**Comment by CGDF-Github** [comment]
@pinterester 1。是
2。否
