### ISSUE TITLE
chenPay中支付二维码窗口直接单击空白处产生问题

### ISSUE THREAD

**Issue by xferget** [NimaQu/ss-panel-v3-mod_Uim#371]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

chenPay中支付二维码窗口若直接单击空白处，不会调用<code>$('#AliPayReadyToPayClose').unbind('click').click</code>窗口便会直接退出，造成<code>AliPayDelete</code>未被执行，计时未被重置。若在此种情况下选择另一支付方式支付，会直接引发混乱

**Comment by xferget** [comment]
@ChenSee

**Comment by ChenSee** [comment]
晚点有时间修一下，买菜去了

**Comment by ChenSee** [comment]
已修复 https://github.com/NimaQu/ss-panel-v3-mod_Uim/commit/379c5a8f1eb3b7b996c7cc7667eed23221d46590
