### ISSUE TITLE
Redundancy QRcode Lib

### ISSUE THREAD

**Issue by SukkaW** [NimaQu/ss-panel-v3-mod_Uim#373]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

> It doesn't matter.

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

**申请添加新的特性或功能或者好的想法**

ss panel v3 mod uim 在 TG 登陆和不同的支付系统分别引入了 `@larsjung/jquery.qrcode` 和 `@davidshimjs/qrcode` 不同的二维码生成依赖库。应当重构去除其中一个。

**Comment by wewall** [comment]
等合并以后用本地吧

**Comment by SukkaW** [comment]
Close due.to the merge of #374
https://github.com/NimaQu/ss-panel-v3-mod_Uim/commit/be98ef36140836a28c426a011a523bf0de801332
