### ISSUE TITLE
为同一个ID的节点添加多个不同的IP的想法

### ISSUE THREAD

**Issue by zylntxx** [NimaQu/ss-panel-v3-mod_Uim#377]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

**申请添加新的特性或功能或者好的想法**

能不能让给同一个ID的节点添加多个不同的IP，在节点列表里面显示多个地址呢
+ 比如添加IPv4和IPv6
+ 比如添加对不同运营商优化的IP
+ 比如添加多个IP分摊被xxx的风险

**Comment by wewall** [comment]
那更新订阅怎么显示呢？节点预留几个备用IP位置了呢？还是多行标注主辅区别呢？

**Comment by zylntxx** [comment]
您看这样可行吗
- 更新订阅以 "节点的名称 - ip的序号" 来订阅
- 备用ip存进node_ip里，多个ip用逗号隔开（这样基本上就不限数量了）
- 不标主辅区别了
- 不同ip产生的流量统计到一起

**Comment by NimaQu** [comment]
https://github.com/NimaQu/ss-panel-wiki/blob/master/ss-panel-v3-mod.wiki/%E8%8A%82%E7%82%B9IP%E5%A1%AB%E5%86%99%E8%A7%84%E5%88%99.md

**Comment by zylntxx** [comment]
@NimaQu 你好，是的我已经看过了这个说明了，谢谢
我希望,给同一个节点添加两个IP让使用者自行选择，比如IPv4与IPv6，这个模块似乎没办法实现呢

**Comment by wewall** [comment]
> @NimaQu 你好，是的我已经看过了这个说明了，谢谢
> 我希望,给同一个节点添加两个IP让使用者自行选择，比如IPv4与IPv6，这个模块似乎没办法实现呢

可以实现，改动太大，需要该库。

**Comment by befantasy** [comment]
也遇到了这个问题。
IPv4 / IPv6这个需求很普遍。
我觉得最简单的实现方式就是只改后台，可以设置多个node id，写数据库的时候往这几个node id里同时写入。

前台不用做任何修改，分别添加每个ip就行了吧。

**Comment by zylntxx** [comment]
> 也遇到了这个问题。
> IPv4 / IPv6这个需求很普遍。
> 我觉得最简单的实现方式就是只改后台，可以设置多个node id，写数据库的时候往这几个node id里同时写入。
> 
> 前台不用做任何修改，分别添加每个ip就行了吧。

@befantasy 
*这么久的 issue 亏你能翻出来*
很久没用 SSP ，信息可能过时
后面的解决方法是**通过源 IP 范围和 ASN 来调度**，这里用到 PerfOps ，可以使用编程模式结合 sni 来实现更加细致的调度（比如域名里带 *"ipv6"* 就返回 ipv6 地址）

**Comment by befantasy** [comment]
哈哈，放狗搜了半天，只搜到这一个有用的信息。。。没想到你还回复的这么快。。。
