### ISSUE TITLE
更新最新文件后的bug

### ISSUE THREAD

**Issue by 74986748** [NimaQu/ss-panel-v3-mod_Uim#378]
1.更新到最新版本后出现网页加载缓慢，一直在显示正在解析主机
2.登录和注册与重置密码的页面的输入框出现重叠，并且点击登录和注册都没有反应
![qq 20181113010236](https://user-images.githubusercontent.com/40517748/48363310-96b04f80-e6e0-11e8-8e78-345e2d5f9e5e.jpg)

**Comment by laurieryayoi** [comment]
上次不是和你说了……1M带宽不够
网页不是刚打开就把东西加载完的，你上次说的网页能快速打开是DNS解析快不是你带宽足
快速打开以后还要加载东西，加载完全这个网页才算完全打开，你带宽不够打开以后下载那些需要加载的东西下的很慢，所以会出现这种情况，能理解吗。

**Comment by 74986748** [comment]
> 上次不是和你说了...... 1M不够带宽
> |网页不是刚打开就把东西加载完的，你上次说的网页能快速打开是DNS快解析不是你带宽足
> 快速打开以后还要加载东西，加载完全这个网页才算完全打开，你带宽不够打开以后下载那些需要加载的东西下的很慢，所以会出现这种情况，能理解吗。

不是服务器问题好吧，你自己看看演示站现在是不是也有这个问题，上次更新了几次文件后不出现加载慢的问题了，今天更新后才出现这个问题，先不说加载的问题，输入框重叠和登录没反应总有问题吧

**Comment by laurieryayoi** [comment]
> > 上次不是和你说了...... 1M不够带宽
> > |网页不是刚打开就把东西加载完的，你上次说的网页能快速打开是DNS快解析不是你带宽足
> > 快速打开以后还要加载东西，加载完全这个网页才算完全打开，你带宽不够打开以后下载那些需要加载的东西下的很慢，所以会出现这种情况，能理解吗。
> 
> 不是服务器问题好吧，你自己看看演示站现在是不是也有这个问题，上次更新了几次文件后不出现加载慢的问题了，今天更新后才出现这个问题，先不说加载的问题，输入框重叠和登录没反应总有问题吧

演示站没问题好吗

**Comment by 74986748** [comment]
挂个国外代理访问网站就没问题，不挂代理并且清除缓存后就会显示正在解析主机
![qq 20181113021032](https://user-images.githubusercontent.com/40517748/48366591-530e1380-e6e9-11e8-8258-b5b93522bc70.jpg)

**Comment by laurieryayoi** [comment]
> 挂个国外代理访问网站就没问题，不挂代理并且清除缓存后就会显示正在解析主机
> ![qq 20181113021032](https://user-images.githubusercontent.com/40517748/48366591-530e1380-e6e9-11e8-8258-b5b93522bc70.jpg)

你f12看一下什么文件加载不出来
![qq 20181113021032](https://puu.sh/C0DvU/20cd757719.png)

**Comment by 74986748** [comment]
> https://cdn.jsdelivr.net/npm/canvas-nest.js@1.0.1
> 所以能打开吗

国内打不开，必须挂代理才能打开

**Comment by laurieryayoi** [comment]
> 国内打不开，必须挂代理才能打开

我可以直连，感觉是地区问题

**Comment by 74986748** [comment]
https://cdn.jsdelivr.net这个连接废了吧，换个链接或本地化吧

**Comment by 74986748** [comment]
> > 国内打不开，必须挂代理才能打开
> 
> 我可以直连，感觉是地区问题

https://cdn.jsdelivr.net这个连接废了吧，换个链接或本地化吧

**Comment by 74986748** [comment]
> > 国内打不开，必须挂代理才能打开
> 
> 我可以直连，感觉是地区问题

登录没反应和重叠也是因为加载不到这个链接的css和js
