### ISSUE TITLE
申请恢复节点二维码配置

### ISSUE THREAD

**Issue by yoyobbs** [NimaQu/ss-panel-v3-mod_Uim#379]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x ] 申请添加新的特性或功能或者好的想法

**申请添加新的特性或功能或者好的想法**
1、申请恢复节点中二维码配置功能
2、申请恢复在“管理面板“-”用户列表”中，能按流量用量排序（管理员可以轻松查到哪些是流量大户）

**Comment by MAOGE2018** [comment]
同样的想法！今天又朋友和我说找不到二维码了！！！

**Comment by MAOGE2018** [comment]
2018.11.16  19:02 我 git pull 了 现在二维码已经出来！ 大家快试试 ！

**Comment by laurieryayoi** [comment]
@MAOGE2018 最起码哪个分支的说一下

**Comment by MAOGE2018** [comment]
> @MAOGE2018 最起码哪个分支的说一下
谢谢提醒 我用的是 master（理解没错的话）
安装命令如下：
git clone -b master https://github.com/NimaQu/ss-panel-v3-mod_Uim.git tmp && mv tmp/.git . && rm -rf tmp && git reset --hard

**Comment by NimaQu** [comment]
节点二维码已修复，流量用量排序为了不让用户多时列表卡住阉割了
