### ISSUE TITLE
无法收到日报

### ISSUE THREAD

**Issue by 497131664** [NimaQu/ss-panel-v3-mod_Uim#381]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容
每日邮件无法收到，手动php xcat sendDiaryMail无任何输出，而发送财务报表会显示Send offline mail to user:  #1。同时邮箱可以正常收到邮件。

**申请添加新的特性或功能或者好的想法**

**Comment by 497131664** [comment]
git show HEAD
commit 379c5a8f1eb3b7b996c7cc7667eed23221d46590
Author: chen <569922982@qq.com>
Date:   Mon Nov 12 10:58:31 2018 +0800

    chenPay中支付二维码窗口直接单击空白处产生问题 bug处理

diff --git a/resources/views/material/user/chenPay.tpl b/resources/views/material/user/chenPay.tpl
index b06d41b..fb692b5 100644
--- a/resources/views/material/user/chenPay.tpl
+++ b/resources/views/material/user/chenPay.tpl
@@ -1,4 +1,3 @@
-
 <style>
     .btn-price {
         margin: 5px;
@@ -16,7 +15,7 @@
     }
 
     #qrcode img {
-        display: initial!important;
+        display: initial !important;
     }
 </style>
 <div class="card-inner">
@@ -190,7 +189,7 @@
                 });
             }
 
-            $('#AliPayReadyToPayClose').unbind('click').click(function () {
+            $('#AliPayReadyToPay').unbind('hide.bs.modal').on('hide.bs.modal', function () {
                 if (CheckPayTimeId) clearTimeout(CheckPayTimeId);
                 if ($id) clearInterval($id);
                 AliPayDelete($order_id);

**Comment by 497131664** [comment]
![qq 20181116004724](https://user-images.githubusercontent.com/32135624/48568198-c8702300-e939-11e8-8e18-ed73639ee6b8.png)

**Comment by NimaQu** [comment]
你用户设置允许接收日报了
