### ISSUE TITLE
[feature request] fast add nodes - add support for OpenWRT router

### ISSUE THREAD

**Issue by WordlessEcho** [NimaQu/ss-panel-v3-mod_Uim#382]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

**申请添加新的特性或功能或者好的想法**
- auto add shadowsocks config (refer: [UCI (Unified Configuration Interface) – Technical Reference](https://openwrt.org/docs/techref/uci))
- check domain ip changes (like: [Auto Update Servers IP](https://github.com/shadowsocks/luci-app-shadowsocks/wiki/Auto-Update-Servers-IP))
- a guide to lead user set up a [crontab](https://openwrt.org/docs/guide-user/base-system/cron) to update everyday

**Comment by CGDF-Github** [comment]
pr is welcome

**Comment by WordlessEcho** [comment]
Please assign this issue to me and keep this issue open.

**Comment by WordlessEcho** [comment]
Close because of API problem #419 and there is a huge work.
