### ISSUE TITLE
dev节点展示逻辑，和管理面板用户信息填写中的说明无法对应

### ISSUE THREAD

**Issue by rico93** [NimaQu/ss-panel-v3-mod_Uim#386]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容
commit 3812ed61da81fa0ea40c4bb47af61f90dbb8741c
Author: laurier <14360417+laurieryayoi@users.noreply.github.com>
Date:   Wed Nov 21 13:38:46 2018 +0800

    修复无普通节点时列表爆炸

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

在用户信息中，用户群组的说明是 ”用户只能访问到组别等于这个数字或0的节点“，但目前用户群组设定成1的情况下，无法在节点列表看到组别为0的节点。 只能看到组别为1的节点。

**Comment by CGDF-Github** [comment]
已修
