### ISSUE TITLE
VIP用户节点不显示单端口多用户

### ISSUE THREAD

**Issue by ouyangmland** [NimaQu/ss-panel-v3-mod_Uim#397]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

VIP用户节点无法显示单端口多用户。普通节点却能显示单端口多用户的节点。

**Comment by laurieryayoi** [comment]
@ouyangmland 承载用户等级要大于所有节点等级

**Comment by ouyangmland** [comment]
> @ouyangmland 承载用户等级要大于所有节点等级

我是管理员账户，设置了20多级
![qq 20181128143706](https://user-images.githubusercontent.com/13723714/49133462-32fe6700-f31b-11e8-8292-8c2834e48dad.png)

**Comment by wewall** [comment]
所以为什么一个显示 一个不显示，心里没点数吗

**Comment by wewall** [comment]
算了你还是让我看看，再喷吧，请执行 `sql`:
```
select name, mu_only from ss_node where name like "%台湾%" ;
```

**Comment by Lins** [comment]
怎么解决的 楼上的兄弟

**Comment by ouyangmland** [comment]
> 怎么解决的 楼上的兄弟

我解决不了这问题。暂时放弃单端口多用户功能。
