### ISSUE TITLE
surge外置模块下载链接失效

### ISSUE THREAD

**Issue by lenovoy450** [NimaQu/ss-panel-v3-mod_Uim#398]
**我确认我已经阅读了** (使用 "x" 选择)

- [ x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ x ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ x ] 反馈一个 bug
- [ x] 申请添加新的特性或功能或者好的想法

虽然在dev里面在用户首页已经隐藏了了这个surge的配置托管的链接，但功能还在。
其中surge配置文件里面的SSEncrypt.module的下载链接已经失效了。
魔改的downloads文件夹自带这个文件，个人建议改为本地化吧。

**Comment by CGDF-Github** [comment]
好的，已删除surge
https://github.com/NimaQu/ss-panel-v3-mod_Uim/compare/dbe8427dabbb...1068694bb150

**Comment by JohnFreeman9** [comment]
> 好的，已删除surge
> [dbe8427...1068694](https://github.com/NimaQu/ss-panel-v3-mod_Uim/compare/dbe8427dabbb...1068694bb150)

相对比于解决问题，解决掉了问题本身更有乐趣（滑稽

**Comment by lenovoy450** [comment]
简单，高效。长痛不如无痛。
