### ISSUE TITLE
超出节点流量上限后，订阅节点依旧显示

### ISSUE THREAD

**Issue by 497131664** [NimaQu/ss-panel-v3-mod_Uim#400]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容
节点设置了流量上限，超出流量上限后，前段已经不显示节点，但是通过订阅连接订阅的用户，还是能够继续看到这个节点

**申请添加新的特性或功能或者好的想法**

**Comment by laurieryayoi** [comment]
@497131664 以前就会显示，节点流量用完只有面板上看不见

**Comment by 497131664** [comment]
> @497131664 以前就会显示，节点流量用完只有面板上看不见

如果这样子的话，那通过订阅使用的用户，就非常容易造成误解啊
