### ISSUE TITLE
更新到 Nov 30, 2018的DEV版本后，小火箭和PC SSR均订阅失败

### ISSUE THREAD

**Issue by sky89757** [NimaQu/ss-panel-v3-mod_Uim#402]
**我确认我已经阅读了** (使用 "x" 选择)

- [ "x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- ["x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新DEV版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

示例网站的单端口多用户订阅也PC无法订阅，https://demo.nimaqu.com/link/gJMS3cfVJvKTaVGB?mu=1
站点已经挂CF，CF规则已设置，安卓端可以正常订阅，PCwin端订阅失败，关闭CF的CDN，也无法订阅，三个测试站有两个出现这个情况，使用的是SSRR，在PC端能直接下载订阅的TXT文件，但是都是订阅失败，无法显示节点。

**Comment by laurieryayoi** [comment]
@sky89757 我自己的测试站测了没问题，请确保你升级的所有步骤都做过一遍

**Comment by CGDF-Github** [comment]
@sky89757 请使用【从sspanel下载的】ssrr

**Comment by sky89757** [comment]
解决了，要打开节点的单多和多端口共存，再关闭多端口，就可以了，PS：示例网站的节点还是没有出来
