### ISSUE TITLE
VM虚拟机下安装节点对接webapimod问题

### ISSUE THREAD

**Issue by JusticeMajin** [NimaQu/ss-panel-v3-mod_Uim#409]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC) 
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

VM虚拟机下安装节点对接使用webapimod
返回信息如下

ERROR webapi_utils.py:31 Error data:{"ret":0,"data":"token or source is invalid, Your ip address is 192.168.0.1"}

IP变为上级路由器IP 而不是公网ip
Centos 7下 可正常yun install
面板节点显示为正常 也能正常反馈测速信息
客户端可正常连结节点 但无法上网

**申请添加新的特性或功能或者好的想法**

**Comment by NimaQu** [comment]
你连的前端在内网？

**Comment by JusticeMajin** [comment]
> 你连的前端在内网？

算在同一个server内 不过对接是使用网域 dns解析回前端主机的

**Comment by NimaQu** [comment]
@JusticeMajin https://github.com/NimaQu/ss-panel-wiki/blob/master/ss-panel-v3-mod.wiki/%E8%8A%82%E7%82%B9IP%E5%A1%AB%E5%86%99%E8%A7%84%E5%88%99.md 参照这个填写多个 ip

**Comment by zhujq971210** [comment]
@NimaQu @nimaqu 快去学习

**Comment by JusticeMajin** [comment]
> @JusticeMajin https://github.com/NimaQu/ss-panel-wiki/blob/master/ss-panel-v3-mod.wiki/%E8%8A%82%E7%82%B9IP%E5%A1%AB%E5%86%99%E8%A7%84%E5%88%99.md 参照这个填写多个 ip

没说清楚 在同一台server内 但是是两台VM
一台前端 一台后端  两台上级路由是192.168.0.1
两台之间对接照正常程序对接 通过网域 dns公网IP
webapi回传说明 后端VM IP却是 路由IP 192.168.0.1而不是公网

**Comment by wewall** [comment]
> > @JusticeMajin 李平：可以用到 iptables 的 nat 技术
> > 有具体思维或做法么? 另外说明 上级路由是软路由 已经nat
> > 双层nat 不知道影响效能不?

这个请教李平先生比较好，毕竟李平先生是这方面的专家

**Comment by JusticeMajin** [comment]
> @JusticeMajin @saberisking

谢主隆恩 
我试试
