### ISSUE TITLE
后台用户列表有几个类别不能鼠标点击排序

### ISSUE THREAD

**Issue by DrawLi** [NimaQu/ss-panel-v3-mod_Uim#413]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)

使用的是Master主分支，不是最新的dev分支。
- [x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

是

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug

后台用户列表 的：

已用流量/GB
总流量/GB
上次使用时间
上次签到时间
邀请人用户名

这几个类目不能在列表点击切换升降序排列。

我意思是比如ID，默认打开后页面是1 2 3 4 5排列，鼠标点击以后会倒序排列：5 4 3 2 1。

有几项无所谓，比如签到等。不过觉得 已用流量/GB 总流量/GB 上次使用时间 还是有用的，希望能修复。

**Comment by SuicidalCat** [comment]
@DrawLi 用戶數量多了頁面卡死/某些數據不能排序自己選一個。

**Comment by DrawLi** [comment]
> @DrawLi 用戶數量多了頁面卡死/某些數據不能排序自己選一個。

这样啊，那可以先放放，不算严重问题。

**Comment by CGDF-Github** [comment]
@DrawLi 如果你加钱，你可以全都要

**Comment by DrawLi** [comment]
> @DrawLi 如果你加钱，你可以全都要

哈哈，有点道理！👍🏻。我非商业，用户就2页多几个，显示选25就出来了。

新版本刚搭建好几天，赵老师的老版本还没迁移过来，好用会捐饮料的。
