### ISSUE TITLE
getUserTraffic 和 getUserClassExpiration 两个函数问题

### ISSUE THREAD

**Issue by rico93** [NimaQu/ss-panel-v3-mod_Uim#428]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容
commit c70732d20b0a24fd8d97a064ffd570174994829f (HEAD -> dev, origin/dev, origin/HEAD)
Author: laurieryayoi <14360417+laurieryayoi@users.noreply.github.com>
Date:   Mon Dec 10 00:51:41 2018 +0800

    <E4><BF><AE><E5><A4><8D><E5><B7><A5><E5><8D><95><E5>9E><E5><A4><8D><E9><A1><B5><E9><97><AE><E9><A2><98>

diff --git a/resources/views/material/admin/ticket/view.tpl b/resources/views/material/admin/ticket/view.tpl

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

今天新用户告诉我说提示账户过期，但是我检查了账户过期日期都是2021年，所以这里数据库没问题。 检查代码的时候发现， line616-638 都是 按照user-class 判断是否过期。 我默认大家都是0。 这里是否应该按照账户实际过期时间来判断。

~~~
	public static function getUserTraffic($user, $is_mu = 0){
        $group_name = Config::get('appName');
		if(!Config::get('mergeSub') and $is_mu == 1){
			$group_name .= ' - 单端口';
		}
		if($user->class !=0){
			$ssurl = "www.google.com:1:auth_chain_a:chacha20:tls1.2_ticket_auth:YnJlYWt3YWxs/?obfsparam=&protoparam=&remarks=".Tools::base64_url_encode("剩余流量：".number_format(($user->transfer_enable-($user->u+$user->d))/$user->transfer_enable*100,2)."% ".$user->unusedTraffic())."&group=".Tools::base64_url_encode($group_name);
		}else{
			$ssurl = "www.google.com:1:auth_chain_a:chacha20:tls1.2_ticket_auth:YnJlYWt3YWxs/?obfsparam=&protoparam=&remarks=".Tools::base64_url_encode("账户已过期，请续费后使用")."&group=".Tools::base64_url_encode($group_name);
		}
      	return "ssr://".Tools::base64_url_encode($ssurl);
	}

    public static function getUserClassExpiration($user, $is_mu = 0){
        $group_name = Config::get('appName');
		if(!Config::get('mergeSub') and $is_mu == 1){
			$group_name .= ' - 单端口';
		}
		if($user->class !=0){
			$ssurl = "www.google.com:2:auth_chain_a:chacha20:tls1.2_ticket_auth:YnJlYWt3YWxs/?obfsparam=&protoparam=&remarks=".Tools::base64_url_encode("过期时间：".$user->class_expire)."&group=".Tools::base64_url_encode($group_name);
		}else{
			$ssurl = "www.google.com:2:auth_chain_a:chacha20:tls1.2_ticket_auth:YnJlYWt3YWxs/?obfsparam=&protoparam=&remarks=".Tools::base64_url_encode("账户已过期，请续费后使用")."&group=".Tools::base64_url_encode($group_name);
		}
~~~

**Comment by CGDF-Github** [comment]
已修复
