### ISSUE TITLE
能否考虑管理面板上新增一个菜单来管理config.php里边的配置项

### ISSUE THREAD

**Issue by realme1065** [NimaQu/ss-panel-v3-mod_Uim#438]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

个人觉得可以在管理面板上新增一个菜单来管理config.php里边的配置项 类似下图这样的，可以存库或者存本地json文件 服务启动时载入到内存中 修改后重载；目前直接取修改php源码太粗暴了 ，并且不太好找，修改起来比较费劲   
![image](https://user-images.githubusercontent.com/18627197/49910567-243cb600-febe-11e8-82ee-014fd172bd75.png)

**Comment by CGDF-Github** [comment]
@realme1065 主要是没空改，需要此功能请氪金

**Comment by NimaQu** [comment]
很久之前就想做 sqlconfig 了，都没时间

**Comment by realme1065** [comment]
我要是会php的话 就帮忙实现了。。🙃都说php是世界上最好的语言    @NimaQu @CGDF-Github
