### ISSUE TITLE
手机端使用chenAlipay问题

### ISSUE THREAD

**Issue by angelsky11** [NimaQu/ss-panel-v3-mod_Uim#440]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

chenAlipay开启后，手机端支付宝付款不会自动跳转到客户端，微信付款长按二维码没反应也不弹出系统菜单保存二维码图片

**Comment by angelsky11** [comment]
@ChenSee

**Comment by angelsky11** [comment]
请问能不能集成一下有赞云支付？

**Comment by galaxychuck** [comment]
不能

**Comment by tonyzzzzzz** [comment]
@angelsky11 不能

**Comment by Anankke** [comment]
@angelsky11 不能

**Comment by mxihan** [comment]
@angelsky11 不能
