### ISSUE TITLE
用户首页添加几个实用功能

### ISSUE THREAD

**Issue by yry0008** [NimaQu/ss-panel-v3-mod_Uim#443]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ x] 申请添加新的特性或功能或者好的想法

1、添加一个.net framework 4.6.2的下载链接（给某些win7用户没有安装的）
2、添加一个tg直连代理选项
3、添加一个反馈链接
实例：https://lonelyi.top
修改的文件：
/resources/views/material/user/main.tpl
[main.tpl](https://github.com/NimaQu/ss-panel-v3-mod_Uim/files/2682386/main.tpl.txt)
/resources/views/material/user/index.tpl
[index.tpl](https://github.com/NimaQu/ss-panel-v3-mod_Uim/files/2682387/index.tpl.txt)

**Comment by CGDF-Github** [comment]
1。没兴趣适配win7，就像没兴趣适配ie一样，机场主有需求自己手动编辑
2。自己写公告里
3。看不见你修改的啥，还要注册你站账号才看得见，自己截个图不行？

**Comment by clhaaaa** [comment]
伸手党可还行
