### ISSUE TITLE
套餐属性覆盖问题～～

### ISSUE THREAD

**Issue by addarmy** [NimaQu/ss-panel-v3-mod_Uim#451]
例如～
A套餐 30天内每1天重置为1G～等级1
B套餐 30天内每1天重置为5G～等级2
用户购买A套餐后，想升级又购买了B套餐～
按理说新的套餐属性应该覆盖旧套餐属性～
结果出现  购买第一天套餐流量确实是5G～
第二天重置后，流量又变成A套餐的1G～
但是等级依然是2级没有问题～
也就是新套餐属性刚购买是覆盖了～第二天又变成了旧套餐属性

**Comment by WooMai** [comment]
@addarmy 商品设置里有选中覆盖吗

**Comment by addarmy** [comment]
额～用的最新dev分支～商品设置里没有覆盖的选项？

**Comment by dalekzhangdong** [comment]
我想升级最新版 怎么升级 有人能帮我高下吗

**Comment by laurieryayoi** [comment]
@dalekzhangdong 开git课，包教包会，一人200，有人报名吗

**Comment by mxihan** [comment]
@dalekzhangdong close-lock一把梭安排一下

**Comment by TBQin** [comment]
新版DEV 编辑用户资料不能保存 问下大佬怎么解决

**Comment by lsbjkc** [comment]
> 例如～
> A套餐 30天内每1天重置为1G～等级1
> B套餐 30天内每1天重置为5G～等级2
> 用户购买A套餐后，想升级又购买了B套餐～
> 按理说新的套餐属性应该覆盖旧套餐属性～
> 结果出现 购买第一天套餐流量确实是5G～
> 第二天重置后，流量又变成A套餐的1G～
> 但是等级依然是2级没有问题～
> 也就是新套餐属性刚购买是覆盖了～第二天又变成了旧套餐属性

我也遇到了同样的问题，请问是如何解决的呀
