### ISSUE TITLE
节点IP自动更换

### ISSUE THREAD

**Issue by JamCh01** [NimaQu/ss-panel-v3-mod_Uim#452]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容
```
commit d2592ed0d024c3ea5c301a7203097aa7c6c97ead
Author: CGDF <17256673+CGDF-Github@users.noreply.github.com>
Date:   Tue Nov 27 02:29:26 2018 +0800
```
2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

有一个问题不知是否算BUG：
添加了A节点，URL:a.example.com IP:1.1.1.1；此时在增加一个中转B（*仅仅为A服务*），IP:2.2.2.2。已经做了DNS解析a.example.com>IP_B，B节点使用Nginx转发流量到A。

好了说了这么一大堆其实就是B中转到A，为什么面板在节点IP的位置写A的IP很快会变成B的IP。

在测试站里面试了一下也是可以复现~

**Comment by Oumig** [comment]
请去这里发https://github.com/NimaQu/ss-panel-v3-mod_Uim

**Comment by JamCh01** [comment]
> 请去这里发https://github.com/NimaQu/ss-panel-v3-mod_Uim

emmm难道不是同一个地方嘛…

**Comment by JamCh01** [comment]
通过注释crontab
```
# */1 * * * * php /www/wwwroot/site/xcat syncnode
```
实现效果

**Comment by eeeeLeeee** [comment]
这个功能应该是给DDNS 动态IP用的，以及在节点被墙，更换IP时，自动去通过域名更新系统里的IP，比如某机器被墙，你更换了IP之后，这里可以自动更新。
但是对于你这种特定中转，以及通过DNS做负载均衡的（就是一个域名后面A很多个IP），就会有点麻烦

现在我想要两个情况（DDNS，以及一个域名后面A多个IP）同时兼容，所以想问一问，节点IP校验是在哪里实现的，我想去将他关闭。或者是后续能不能增加一个功能，就是每个节点可以选择开启自动更新IP以及不自动更新IP
