### ISSUE TITLE
最新DEV不能编辑用户

### ISSUE THREAD

**Issue by TBQin** [NimaQu/ss-panel-v3-mod_Uim#456]
![qq 20181223104504](https://user-images.githubusercontent.com/25794322/50381447-68039c80-06c2-11e9-82e9-e4690f5f8feb.png)
![22](https://user-images.githubusercontent.com/25794322/50381448-69cd6000-06c2-11e9-9cf8-d7a73bc8159e.png)
显示这个问题 问下大佬怎么解决 挂了CF的

**Comment by laurieryayoi** [comment]
关掉CF清缓存
