### ISSUE TITLE
关于节点IP自动通过域名更新的建议

### ISSUE THREAD

**Issue by eeeeLeeee** [NimaQu/ss-panel-v3-mod_Uim#457]
**我确认我已经阅读了** (使用 "x" 选择)

- [ x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x ] 申请添加新的特性或功能或者好的想法

**申请添加新的特性或功能或者好的想法**

节点IP现在会根据域名解析到的IP自动更新。
可以通过注释掉一条计划任务关闭自动更新（# */1 * * * * php /www/wwwroot/site/xcat syncnode）
但是注释后会完全关闭掉所有的自动更新。DDNS的机器也只能通过mysql回调数据了，然而合租机器直接给mysql有点危险。
所以想问问能不能有以下解决方案
1.给每个节点提供syncnode的单独的是否开启的选项。
2.关闭web回调校验IP的功能

如果是第二种解决方式，肯定没法直接合并进入项目里，能不能直接给出在哪里实现的校验IP，我直接自己改掉即可。谢谢

**Comment by NimaQu** [comment]
app/Middleware/Mod_Mu.php
