### ISSUE TITLE
关于演示站的 人机安全校验

### ISSUE THREAD

**Issue by stardock** [NimaQu/ss-panel-v3-mod_Uim#458]
**我确认我已经阅读了** (使用 "x" 选择)

- [ X] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [X ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ X] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ X] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ X] 申请添加新的特性或功能或者好的想法

**申请添加新的特性或功能或者好的想法**

我没有在模板中找到你演示站点的这个 人机安全校验 模块。
貌似国内和国外访问时还走的不一样的API，能否告知下是怎么做的。 我想做一个和演示站点一样的。

**Comment by NimaQu** [comment]
@stardock Cloudflare Firewall

**Comment by stardock** [comment]
thanks
