### ISSUE TITLE
关于最近的密码爆破的一些想法

### ISSUE THREAD

**Issue by eeeeLeeee** [NimaQu/ss-panel-v3-mod_Uim#465]
最近羊事件沸沸扬扬= =，关于他的用户密码被爆破方面，一方面是由于其没更改默认盐，导致可以直接使用现有的彩虹库进行对比。另一方面，即使更改了盐，生成彩虹表后也可以进行批量爆破。对此有一些想法：
首先是使用专门用于密码的hash算法，在之前的pr中就有提到Argon2。
另一方面，应该给每个用户生产单独的盐，这样在进行爆破的时候需要针对每个盐单独生成彩虹表，难度大大增加。
这也是常见的保护用户密码的方法。在即使被脱裤的情况下，也能亡羊补牢。
最后，等哪位好心人有空了来写下。

**Comment by CGDF-Github** [comment]
这个问题说严重是严重，说不严重的话也的确不严重。。。毕竟，如果站长不作死（比如小鸡使用弱密码），一般被爆库的可能性很低，而且开发组精力很有限，所以重写这方面设计的可能性不大。。。
so, pr is welcome.

**Comment by mxihan** [comment]
@CGDF-Github 最重要的问题不是如何防止加密后密码被爆破，而是如何防止数据库泄露

**Comment by glzjin** [comment]
就个人观点来说都得预防~

**Comment by Indexyz** [comment]
换成 bcrypt 吧

**Comment by eeeeLeeee** [comment]
> @CGDF-Github 最重要的问题不是如何防止加密后密码被爆破，而是如何防止数据库泄露

亡羊补牢，几手准备嘛。确实现有面板再做这种大改，老站完全没法迁移。只是提出一个最佳实践，也可以运用到其他项目中的开发。

**Comment by xcxnig** [comment]
@Indexyz Google Facebook Twitter 都在用

**Comment by Indexyz** [comment]
问题是 中途换密码加密方式要求全部用户重置密码

**Comment by eeeeLeeee** [comment]
http://php.net/manual/zh/faq.passwords.php#faq.passwords.fasthash

**Comment by Anankke** [comment]
即使给每个用户生产单独的盐也不需要攻击者生成巨量的彩虹表进行加速攻击，都可以使用巨量计算实时破译
事实上，只要加上了盐值彩虹表就用不上了
当前的办法更推荐把在 conf 文件中默认无盐值设定进行提醒
即使未加盐，目前互联网上并没有针对目前使用的 SHA256 算法通用广泛彩虹表
以及，你永远无法阻止你的用户使用弱密码
bcrypt 的破解速度虽然只有数万每秒（1080TI, 2018/12）,但是只要用户使用了前一千万内的弱密码，仍旧可以在几十秒钟内破解出来
相似的，MD5 可以达到千亿的速度，但是如果使用了密码生成器，破解也要花很长时间
所以要培养用户的良好密码习惯（迫真）
