### ISSUE TITLE
我升级前端得以下错误提示，我不知道哪里出错了？？

### ISSUE THREAD

**Issue by qsyssr** [NimaQu/ss-panel-v3-mod_Uim#466]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@VM_0_6_centos.(none)')

这是哪里有问题？哪位大神解答下？

**Comment by eeeeLeeee** [comment]
已经写了错误提示了

**Comment by qsyssr** [comment]
> 已经写了错误提示了

小白不知道怎么解决，大神能否给点提示？

**Comment by eeeeLeeee** [comment]
你没有写清楚你执行了什么然后返回了什么。
git教程：https://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000#0
提问的艺术：
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

**Comment by qsyssr** [comment]
> 你没有写清楚你执行了什么然后返回了什么.git 
> 教程：[https](https://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000#0)：//www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000#0 
> 提问的艺术：[https](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)：
> [//github.com/ryanhanwu/How-To-Ask -Questions最聪明的路](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)

我执行了git pull升级前端给出的错误提示
