### ISSUE TITLE
码支付当面付二合一   f2fpay_codepay 设置了没效果。很急

### ISSUE THREAD

**Issue by mimi8280** [NimaQu/ss-panel-v3-mod_Uim#467]
我设置f2fpay_codepay 码支付和当面付二合一，可是没有任何作用,dev和master分支都没有鲜果，设置了f2fpay_codepay 前端只显示充值码这界面。没有出来二合一的效果，很急，希望老大解决下bug

**Comment by xcxnig** [comment]
@mimi8280 最新版把f2fpay_codepay 删掉了 忘记把选项删掉了

**Comment by mimi8280** [comment]
能否添加这个功能，因为和我一样的也有很多人想用，因为支付宝的当面付稳定，码支付的话解决下微信，这样合二为一了。我有群里个朋友也是和我一样，他说估计废弃掉了。希望老大能否添加下。需求人还是有的。好像master分支就要整合这星期，能否整合进去。谢谢老大们了。

**Comment by lenovoy450** [comment]
既然砍了，说明有更好的选择. 
如果选择保留，可以使用旧的呀. 以及自己改回去呗. 
机场已经收钱收到迫不及待，就给项目组捐点，找大佬改回去吧.

**Comment by mimi8280** [comment]
我个人意见捐过钱，一开始使用老大程序就捐过。需要再捐款也义不容辞，老大能否帮忙改下呢？

**Comment by ligengwen** [comment]
我还在使用旧版本master的也是使用的f2fpay_codepay 二合一 新版dev已经把这个砍掉了？

**Comment by NimaQu** [comment]
@ligengwen 早砍了

**Comment by lenovoy450** [comment]
> 我个人意见捐过钱，一开始使用老大程序就捐过。需要再捐款也义不容辞，老大能否帮忙改下呢？
留联系方式私聊吧。

**Comment by lenovoy450** [comment]
> 我个人意见捐过钱，一开始使用老大程序就捐过。需要再捐款也义不容辞，老大能否帮忙改下呢？

留联系方式私聊吧。

**Comment by ligengwen** [comment]
@mimi8280 你好你是否解决这个问题

**Comment by mimi8280** [comment]
@ligengwen 你也需要解决和我一样的问题？

**Comment by ligengwen** [comment]
@mimi8280 是的。。急需

**Comment by mimi8280** [comment]
@mimi8280 他们都说被砍了。所以老大们都不高兴解决。哎

**Comment by lenovoy450** [comment]
> @ligengwen 他们都说被砍了。所以老大们都不高兴解决。哎

说了付费定制，你又不来做？
