### ISSUE TITLE
请求提供除docker后端外的一键脚本后端

### ISSUE THREAD

**Issue by chenyitian2004** [NimaQu/ss-panel-v3-mod_Uim#470]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

请求提供除docker后端外的一键脚本后端
我的节点主机商不允许更换内核，用的是内核版本2.x的centos7，无法运行docker，请求大佬出个一键脚本，谢谢！
之前用肥羊的脚本数据库方式和webapi方式都对接不上，不知道是什么原因，之前用肥羊的前端就能对接上

**Comment by laogao123** [comment]
@chenyitian2004 可以试试我上面那个一键脚本呢

**Comment by SuicidalCat** [comment]
@laogao123 搶著提供脚本還行，，

**Comment by laogao123** [comment]
@SuicidalCat 哈哈哈，刚好手上有脚本呢。

**Comment by eeeeLeeee** [comment]
docker本身基本不影响性能，而且会隔离环境让机器也更安全（虽然做节点本来就没什么数据）。
主要是，还会统一环境，不然编译和安装还会可能出各种各样的问题。

**Comment by chenyitian2004** [comment]
但是我前端还是连接不上后端，请问大佬们应该是哪里出了问题呢

**Comment by SuicidalCat** [comment]
@chenyitian2004 大腦升級，請

**Comment by eeeeLeeee** [comment]
应该是后端连前端
你需要看日志

**Comment by chenyitian2004** [comment]
日志在/soft/shadowsocks下的哪里呢。。

**Comment by SuicidalCat** [comment]
@chenyitian2004 ssserverlog

**Comment by eeeeLeeee** [comment]
1.你使用docker能连接上么
2.用的web还是mysql
3.能不能别用openvz的机器当节点，性能吃不消

**Comment by chenyitian2004** [comment]
1.docker不能连接上
2.web和mysql都不行
3.现在用的腾讯云KVM小鸡。。

**Comment by eeeeLeeee** [comment]
所以其实你的问题是，你根本就没连上过对吧。。
用腾讯云KVM，是可以换内核的。
另外，腾讯云当节点是什么操作
不要用古董系统了，立即使用ubuntu18.04

**Comment by chenyitian2004** [comment]
不能换内核的是另外一个服务商，他给我开的ovz，我只在用肥羊前端的时候用肥羊的后端一键脚本连上过，待会换个系统试试，不知道有没有可能是之前肥羊的面板残留导致的
