### ISSUE TITLE
【30/12/2018】更新后 界面缺少css

### ISSUE THREAD

**Issue by regendsoh** [NimaQu/ss-panel-v3-mod_Uim#471]
![image](https://user-images.githubusercontent.com/17229500/50547725-6580e400-0c7a-11e9-907f-b8bc236b4590.png)

如图所示，很可能缺少一个很重要的css

**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [X] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

commit 6ceb36139289f8e31d77950090fe742b9da1316d
Merge: d2592ed 4de3d42
Author: NimaQu <i@nimaqu.com>
Date:   Sun Dec 30 20:42:01 2018 +0800

    Merge branch 'dev'

diff --cc resources/views/material/user/main.tpl
index 9a9f6cb,f9cd3a8..132c2c7
mode 100644,100755..100644
--- a/resources/views/material/user/main.tpl
+++ b/resources/views/material/user/main.tpl
@@@ -378,12 -99,7 +99,6 @@@
                                                                        <i class
                                                                </a>
                                                        </li>
-
-
-
-
-
-
 -
:...skipping...
commit 6ceb36139289f8e31d77950090fe742b9da1316d
Merge: d2592ed 4de3d42
Author: NimaQu <i@nimaqu.com>
Date:   Sun Dec 30 20:42:01 2018 +0800

    Merge branch 'dev'

diff --cc resources/views/material/user/main.tpl
index 9a9f6cb,f9cd3a8..132c2c7
mode 100644,100755..100644
--- a/resources/views/material/user/main.tpl
+++ b/resources/views/material/user/main.tpl
@@@ -378,12 -99,7 +99,6 @@@
                                                                        <i class="icon icon-lg">loyalty</i>&nbsp;邀请链接
                                                                </a>
                                                        </li>
-
-
-
-
-
-
 -
                                                </ul>

diff --cc resources/views/material/user/trimepay.tpl
index bcde466,5b91955..573b1f2
--- a/resources/views/material/user/trimepay.tpl
+++ b/resources/views/material/user/trimepay.tpl
@@@ -1,25 -1,18 +1,14 @@@
- <div class="row">
--
-         <div class="col-lg-6 col-md-6">
-             <p class="card-heading">TrimePay 充值</p>
 -
 -    <div class="card-inner">
++   <div class="card-inner">
+             <p class="card-heading">输入充值金额后，点击下方的图标进行充值</p>
              <div class="form-group form-group-label">
                  <label class="floating-label" for="amount">金额</label>
                  <input class="form-control" id="amount" type="text" >
              </div>
          </div>
-         <div class="col-lg-6 col-md-6">
-             <p class="h5 margin-top-sm text-black-hint" id="qrarea"></p>
-         </div>
- </div>
-
-     <div class="card-action">
-         <div class="card-action-btn pull-left">
-             <br>
+         <div id="qrarea">
              <button class="btn btn-flat waves-attach" id="btnSubmit" name="type" onclick="pay('Alipay')"><img src="/images/alipay.jpg" width="50px" height="50px" /></button>
-             <button class="btn btn-flat waves-attach" id="btnSubmit" name="type" onclick="pay('WEPAY_QR')"><img src="/images/weixin.jpg" width="50px" height="50px" /></button>
+             <button class="btn btn-flat waves-attach" id="btnSubmit" name="type" onclick="pay('WEPAY_JSAPI')"><img src="/images/weixin.jpg" width="50px" height="50px" /></button>
          </div>
-     </div>
-
 -
 -
  <script>
      var pid = 0;

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

**Comment by NimaQu** [comment]
@regendsoh cache

**Comment by regendsoh** [comment]
跪求大神原谅 我错了 浏览器cache
