### ISSUE TITLE
建议增加TG机器人的订阅功能

### ISSUE THREAD

**Issue by SaylerYang** [NimaQu/ss-panel-v3-mod_Uim#476]
建议添加用户的订阅地址到TG机器人，最好还可以分类订阅，实现不用开网页就可以完成基本操作。

**Comment by Anankke** [comment]
pr welcomed

**Comment by SakuraSa233** [comment]
pr welcomed

**Comment by glzjin** [comment]
pr welcomed

**Comment by CGDF-Github** [comment]
https://github.com/NimaQu/ss-panel-v3-mod_Uim/pull/482
