### ISSUE TITLE
当transfer_enable=0时，500报错

### ISSUE THREAD

**Issue by ImDebugger** [NimaQu/ss-panel-v3-mod_Uim#479]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**
大佬们好，按流程搭建，全部是git拉取的文件，
centos 7 + 宝塔+ PHP7.2 +  mysql5.5 
当任意用户数据库内 transfer_enable =0 的时候，在用户中心就会有这个报错。 
演示站并无复现。请大佬指点下

![1](https://user-images.githubusercontent.com/30263900/50588845-e6302200-0ebe-11e9-9427-6f561bbc0fc3.png)

**Comment by CGDF-Github** [comment]
fixed

**Comment by CGDF-Github** [comment]
fixed, again.
https://github.com/NimaQu/ss-panel-v3-mod_Uim/commit/af82da56689ae6060fd30770e616943bbeb65250
