### ISSUE TITLE
footer.tpl插入统计代码小BUG

### ISSUE THREAD

**Issue by 1187558419** [NimaQu/ss-panel-v3-mod_Uim#480]
**反馈BUG**
/www/wwwroot/sspanel3uim/resources/views/material/user
/www/wwwroot/sspanel3uim/resources/views/material/admin
分别在上面两个文件夹下的footer.tpl文件中。
`	<footer class="ui-footer">
		<div class="container">
			<marquee>&copy;2017-{date("Y")} {$config["appName"]} | Powered by <a href="/staff">SSPANEL</a> {if $config["enable_analytics_code"] == 'true'}{include file='analytics.tpl'}{/if} </marquee> 
		</div>
	</footer>`

</marquee> 应该移动至if语句之后，不然的话加入的统计脚本是静止没有滚动的。
并且admin/footer.tpl文件中<marquee>标签缺少“/”。

**Comment by CGDF-Github** [comment]
`enable_analytics_code`删了算了。。。。
