### ISSUE TITLE
建议：增加英文版

### ISSUE THREAD

**Issue by lKingl** [NimaQu/ss-panel-v3-mod_Uim#490]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

**申请添加新的特性或功能或者好的想法**

请问有翻译为英文的想法吗？如果可以的话我希望能提供一些帮助。

**Comment by glzjin** [comment]
pr welcome

**Comment by galaxychuck** [comment]
pr welcome

**Comment by lKingl** [comment]
okay thanks

**Comment by safepayment** [comment]
请问这个后续有推进么？

**Comment by Anankke** [comment]
没有

**Comment by lKingl** [comment]
我目前是直接多加一个模板实现的，后面的更新就没有更了。不过可以用vue-i18n实现多语言，改动还是很多，大佬想做的话我依然很乐意再来翻译 XD

**Comment by FIERCELION** [comment]
仍然需要英文版，希望继续推进！
