### ISSUE TITLE
等级和帐号剩余天数，电脑显示正常，手机浏览器不显示

### ISSUE THREAD

**Issue by caiwenjie007** [NimaQu/ss-panel-v3-mod_Uim#51]
电脑端：
![ABC](http://img.7s8.net/temp/1804/8d50e0ccefc05465.jpg) 

手机端：
![ABC](http://img.7s8.net/temp/1804/da0052136dfd87d2.png)

**Comment by NimaQu** [comment]
ios 设备无法显示这个问题已知，我们引用了 https://github.com/CloudHammer/make-sspanel-v3-mod-great-again 的代码，建议[点击这里](https://github.com/CloudHammer/make-sspanel-v3-mod-great-again)去向它们提交一个 issus

**Comment by caiwenjie007** [comment]
好我去提交
