### ISSUE TITLE
开启Geetest验证码后出现的问题

### ISSUE THREAD

**Issue by itmihang** [NimaQu/ss-panel-v3-mod_Uim#52]
测试环境 
    1. PC（Chrome 66.0.3359.117， IE 11.371） 
    2. Samsung Galaxy S9 Android 8.0
    3. iPhone 8 Plus 10.33
当开启Geetest验证码后出现的三个问题
    1. 签到功能无法使用，关闭验证功能后正常
    2. 注册失败后，验证码无法更新，保持验证成功状态，需要手动刷新
    3. 登陆失败后，验证码无法更新，保持验证成功状态，需要手动刷新

**Comment by NimaQu** [comment]
2和3都是历史遗留问题了....1我找个时间修一下，因为钱爸爸之前改的时候直接删了
