### ISSUE TITLE
建议：增加背景修改

### ISSUE THREAD

**Issue by wewall** [NimaQu/ss-panel-v3-mod_Uim#55]
建议在[.config.php](https://github.com/NimaQu/ss-panel-v3-mod_Uim/blob/master/config/.config.php.example)文件中加入:[/index.tpl](https://github.com/NimaQu/ss-panel-v3-mod_Uim/tree/master/resources/views/material/index.tpl)中[/assets/css/main.css](https://github.com/NimaQu/ss-panel-v3-mod_Uim/tree/master/public/assets/css/main.css)文件的背景替换设置，每次更新都会替换回去，换[CDN源](https://github.com/NimaQu/ss-panel-v3-mod_Uim/commit/4a941d7fdf812134d7bc4c9f0394f0e9ca5707cf)的话还得修改也比较麻烦每次，希望在[.config.php](https://github.com/NimaQu/ss-panel-v3-mod_Uim/blob/master/config/.config.php.example)中新增

1.示例文字修改设置
2.背景替换设置

**Comment by mxihan** [comment]
建议阅读这个内容https://git-scm.com/book/zh/v2/Git-%E5%B7%A5%E5%85%B7-%E5%82%A8%E8%97%8F%E4%B8%8E%E6%B8%85%E7%90%86
