### ISSUE TITLE
邀请码建议

### ISSUE THREAD

**Issue by caiwenjie007** [NimaQu/ss-panel-v3-mod_Uim#61]
目前的邀请码只显示一个为了美观，这点赞同。但是可以改成邀请一个之后，再变换一个吗，
现在是固定的，每次邀请别人，再邀请下一个人，邀请码总是同一个不变

**Comment by NimaQu** [comment]
这是为了方便用户类 whmcs 的邀请返利而设计的，如果需要控制注册数量请调整您的邀请码数量，邀请码数量即链接可用次数

**Comment by caiwenjie007** [comment]
可是这个邀请码要是被别人发现固定的，不是会有恶意注册，whmcs那个有变通方案吗

**Comment by caiwenjie007** [comment]
或者加一个重置邀请链接按钮，每次我手动重置一下呢

**Comment by mxihan** [comment]
@caiwenjie007 whmcs也是固定aff

**Comment by NimaQu** [comment]
手动重置的话，数据库有张存邀请链接的表，你把他全删了就行

**Comment by caiwenjie007** [comment]
@mxihan  whmcs是固定的我知道，国外卖VPS的whmcs aff链接都是固定的

@NimaQu 你可以考虑下，config加个设置项，如果是whmcs，就显示一个固定的，如果非whmcs，就在前台加个重置链接按钮，
