### ISSUE TITLE
请问魔改能出一个删号白名单吗

### ISSUE THREAD

**Issue by Nekoer** [NimaQu/ss-panel-v3-mod_Uim#64]
开了自动删号，然后把账户上有钱的给自动删了

**Comment by Nekoer** [comment]
然后有些用户是公司用的，也被删了

**Comment by mxihan** [comment]
https://github.com/NimaQu/ss-panel-v3-mod_Uim/commit/7f20a52f67d417fd39da57b421c5a01e6554ae13
