### ISSUE TITLE
提醒一下关于版权的问题

### ISSUE THREAD

**Issue by XiaoPika** [NimaQu/ss-panel-v3-mod_Uim#76]
根据一位梯子铺的老板说的，首页面板是fork源自本项目，然而首页面板貌似是使用了 [html5up的一款free demo](https://html5up.net/dimension) 但删去了版权信息。

<br>

![](https://i.loli.net/2018/05/11/5af553bd6c0a1.jpg)
![](https://i.loli.net/2018/05/11/5af554e379c7d.jpg)
![](https://i.loli.net/2018/05/11/5af553bf79e2b.jpg)

<br>
原作版权要求：https://html5up.net/license，供各位大佬参考一下。

**Comment by FQrabbit** [comment]
@XiaoPika 版权海星。。。

**Comment by XiaoPika** [comment]
2333，因为曾经用过这个Demo所以。。。有些强迫s

**Comment by galaxychuck** [comment]
@XiaoPika 版權一直在

**Comment by mxihan** [comment]
@FQrabbit 项目中版权信息并未删除，删除版权信息为个人做法，本项目开发人员无力干预

**Comment by XiaoPika** [comment]
@mxihan 抱歉，由于没有部署过本项目，没有考证项目是否删除版权信息，采信了梯子铺老板的一面之词，对给各位大佬造成的困扰表示歉意。

**Comment by mxihan** [comment]
@XiaoPika close

**Comment by mxihan** [comment]
@mxihan 页面源码的注释、css 的注释里均有保留

**Comment by XiaoPika** [comment]
![](https://i.loli.net/2018/05/11/5af55738bb68f.jpg)
![](https://i.loli.net/2018/05/11/5af557763d120.jpg)

总觉得这样放在注释里是不是不太符合版权要求吧。。
至少也应该放在 resources/views/material/staff.tpl 里吧

**Comment by galaxychuck** [comment]
@XiaoPika 如果你有條件，可以來這裡 https://t.me/sspanel_Uim 反應你的想法(

**Comment by XiaoPika** [comment]
@galaxychuck 因为我跟梯子铺的老板不抱希望的提了一下就很痛快的改了，所以顺便在这里也提一下，本来只是建议而已，改不改跟我也没关系，非常抱歉占用各位大佬时间，再见~

**Comment by XiaoPika** [comment]
D我啊？请随意 :)
比以前的破娃还不堪

**Comment by xcxnig** [comment]
如果认为侵权，请发律师函，谢谢。
