### ISSUE TITLE
为何充值金额都是选择式的？

### ISSUE THREAD

**Issue by jmireles7** [NimaQu/ss-panel-v3-mod_Uim#79]
当面付和Spay，毕竟有AFF奖励，然后这金额就尴尬了，可以考虑设置一个最低充值金额判断，这样感觉更人性化一点。

**Comment by NimaQu** [comment]
@jmireles7 然后改成输入式又有人问为什么不改成选择式

**Comment by mxihan** [comment]
@NimaQu 所以说加个判断金额就好了嘛

**Comment by jmireles7** [comment]
@NimaQu @mxihan 
对头，自定义输入金额+判断最金额才是最佳方案。
接到工单要充值选择里没有的金额，虽然只是偶尔，并不是太多，但是总觉得比别扭，自己瞎改了改，技术有限没成功 - -
最后只好加了几个不是套餐金额的金额选项，
然后我经常发现有用户是拼凑金额的，
比如他要充35，连续充了3次10块和一次5块……

**Comment by ccwy** [comment]
这是自定义充值金额的，抄的前面的代码。。。。


    private static function spay_html($user)
    {
        return '
						<form action="/user/alipay" method="get" target="_blank" >
							<p class="card-heading">支付宝充值</p>
							<p>充值金额:
			  <input class="form-control" id="type" name="amount" placeholder="输入充值金额后，点击提交即可" autofocus="autofocus" type="number" min="20" max="1000" step="1" required="required"></p>
                
							<input type="submit" value="提交" />
						</form>
';
    }

**Comment by jmireles7** [comment]
@ccwy   
感谢帮助，大佬发的代码Spay可以使用，但套到f2fpay就会“订单金额错误”，

**Comment by mxihan** [comment]
@jmireles7 你把整段复制过去的吗。。。整段复制过去当然会出错误

**Comment by NimaQu** [comment]
已跟进，请查看最新 commit

**Comment by MAOGE2018** [comment]
昨天更新了一下，可以自己输入了，第一次学习git pull😂，不知道发生了什么就成功了:)

**Comment by xfzxfz123** [comment]
@NimaQu  我充了21并未到账，，，，还请修复，，用户名
Kannagi_Yuuri

**Comment by wewall** [comment]
@xfzxfz123 傻逼吧，你在哪儿充的钱找谁去。

**Comment by galaxychuck** [comment]
@xfzxfz123 傻逼吧，你在哪儿充的钱找谁去。

**Comment by NimaQu** [comment]
@xfzxfz123 傻逼吧，这里是 github 不是贴吧
