### ISSUE TITLE
[BUG]逻辑判断改进

### ISSUE THREAD

**Issue by wewall** [NimaQu/ss-panel-v3-mod_Uim#84]
在注册时不填写邮箱或者错误填写,点击发送验证码会进入周期计时
![image](https://user-images.githubusercontent.com/33481440/40154777-b4729aba-59c2-11e8-8463-c9b5ea323b4b.png)
![image](https://user-images.githubusercontent.com/33481440/40154780-b794653e-59c2-11e8-9f8d-3a145a43bacd.png)

**Comment by NimaQu** [comment]
@wewall 智商不够 时间来凑
