### ISSUE TITLE
 Authentication failed for 'https://github.com/galaxychuck/ss-panel-v3-mod_UIChanges.git/'

### ISSUE THREAD

**Issue by 15520000820** [NimaQu/ss-panel-v3-mod_Uim#92]
v3-mod_UIChanges.git tmp && mv tmp/.git . && rm -rf tmp && git reset --hard
Cloning into 'tmp'...
Username for 'https://github.com':
Password for 'https://github.com':
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/galaxychuck/ss-panel-v3-mod_UIChanges.git/'
[root@vultr ss.yangyaoyu.cn]#  Authentication failed for 'https://github.com/galaxychuck/ss-panel-v3-mod_UIChanges.git/'
-bash: Authentication: command not found
 是需要购买吗?  感觉 READE ME里面要应该说明一下

**Comment by ZJY2003** [comment]
请仔细阅读[教程](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/SS-PANEL-%E7%BD%91%E7%AB%99-%E5%89%8D%E7%AB%AF%E5%AE%89%E8%A3%85)

galaxychunk的sspanelV3库已rm
