### ISSUE TITLE
可否添加人工增加用户的功能

### ISSUE THREAD

**Issue by Chennhaoo** [NimaQu/ss-panel-v3-mod_Uim#93]
非常感谢大佬的代码，我试了试dome网站，发现管理员面板没有人工增加用户的选项，只能自己注册。请问会有增加这个功能的打算吗？<br>关闭注册功能我准备通过删除注册界面的注册按钮来实现，不知道这样如何。<br>

**Comment by xcxnig** [comment]
@Chennhaoo 没有这个打算，你要需要的话，你可以付费定制

**Comment by Chennhaoo** [comment]
感谢各位解答，我先找找代码，看自己能搞定不。
