### ISSUE TITLE
支付二维码不显示

### ISSUE THREAD

**Issue by Sunshine0045** [NimaQu/ss-panel-v3-mod_Uim#98]
大佬，我问一下那个f2fpay的二维码不显示了，怎么解决呀？我搜了一下没有找到答案，或许是我搜的方法不对。希望大佬们能够给我提示一下解决的方法。谢谢。

**Comment by NimaQu** [comment]
@Sunshine0045 百度云把二维码支付 api 关了

**Comment by NimaQu** [comment]
@Sunshine0045 百度云把二维码生成 api 关了

**Comment by mxihan** [comment]
@NimaQu 百度云把二维码生成的API关闭了，项目将会在下次版本更新中更换API修复

**Comment by Sunshine0045** [comment]
好的，我知道了。谢谢大佬。
